### ISSUE TITLE
Always indexing @ startup

### ISSUE THREAD

**Issue by remielowik** [haiwen/seafile#1002]
When seafile is started(usually @ windows startup) it seems it tries to index the hole map, since this is a big map it just keeps on indexing.

**Comment by lins05** [comment]
It has to do this. Otherwise how can seafile know if there is any file
changed during the time seafile was not running?

**Comment by remielowik** [comment]
Well I think it should be an option atleast for it to not index @ startup. Currently its indexing for more then 24 hours, which was fine when for the first time but since it does that at every startup its unacceptable(indexing takes longer then my computer is on), futhermore I always run seafile so i dont see why it should index because no files will be changed when its off because then my pc will be off. Also the large map was in my dropbox folder, dropbox took less then 15 minutes to start thus why can dropbox do what seafile cant?

**Comment by GITchristoph** [comment]
Hi Guys
We are experiencing the same "issue" (only with the windows client).
In a nutshell:
Mac clients starts after a reboot and indexes a 95 gig Library and is operational in "no time" (less than 20-30 seconds). Windows client needs for the same task 45 minutes, mainly indexing the 95 gig Library.

I posted that in Seafile Google Groups a while ago (logs etc.). https://groups.google.com/forum/#!searchin/seafile/indexing/seafile/Bj7p0Y3jDv0/KqhooO15fnYJ

I never got anywhere to improve this.
Even if you just restart the windows client without restarting the PC it reindexes for 45 minutes.

**Comment by freeplant** [comment]
@remielowik  How many files do you have in the library?

@GITchristoph Because Mac use SSD, which is much faster than normal disk.

**Comment by remielowik** [comment]
About 500k files, but I do notice it takes alot less time @ my desktop(7200rpm vs 5400rpm laptop) but still it takes around 4 hours.

**Comment by GITchristoph** [comment]
Hi Freeplant

Sorry that I am coming back that late. Was a bit busy.
I checked today again and found out that the seafile client on the windows computer is indeed having the files stored on a normal disk, not on an SSD. The Laptop has 2 disks and only the OS is running on an SSD. I got that wrong in  the first place, I always thought that all Mac and PC's fully run on SSD's.

**But even if that's a logical explanation I am asking myself:**

Doesn't that mean that when Seafile works like this, that then only SSD equipped Computers are capable to handle (let's say something like) > 50GB Libraries? 
So all Laptops / Computers with normal disks are not really fit for purpose for large Libraries on Seafile then, if you can't afford to wait for more than 30 minutes until Seafile stops indexing and starts syncing?
Or up to 4 hours as experienced by remielowik on his pretty large Library.

Is that really wanted? 

In our experience it's not like that on btsync, owncloud or on dropbox on the same PC, that's why we hope that there might be a possibility to improve that in Seafile somehow.

I am sorry that I am going on and on about that topic. Seafile works so great for us and we appreciate all the work and effort that is being put into this by the developers. This is just an item that really effects us on our everyday work life and that we wish so much that this could get improved somehow or at least would be considered worth optimising not only by ourselves.

**Happy New year to everybody,** (for everybody not on Chinese calendar ;-) )

Chris

**Comment by killing** [comment]
Well, we'll work on the improvement. Currently I can see a few possible directions:
1. We don't use the native Windows API to list the directory tree. The performance may be improved with native API.
2. The scanning procedure needs to scan the directory tree twice. This is wasteful and can be combined into one pass.

**Comment by GITchristoph** [comment]
Hi killing,
This sounds promising.
Unfortunately we are pure users and not able to develop there. But I started a python course online. Who knows, maybe in 10 years I will be able to support ;-)

KR, Chris

**Comment by crogsch** [comment]
I would like to add a comment on that, because I have the same issue. Because indexing is necessary on each system restart (client), I have running my computers 24/7 except the weekend (I shut down them on friday and start up on sunday, thus they have indexed all content on monday morning). Due to a power failure (at the morning) I had also the same problem with indexing, that libraries were not indexed, but staff starts working...

For my situation, I have two solutions (simple and "best" solution):
Simple solution:
Because I have more than 100 different libraries, it would be very helpful, if the indexing-order of the client is based on the timestamp the library has on the server, this means that libraries with the most recent timestamp (or change or however we will call it) are indexed first on the different clients. Thus we are working on only a few libraries each day, the other libraries are synced later, which does not matter...

Best solution:
The "best" solution would be (because different computers work on different libraries), if the client could use informations from the the server, thus the syncing/indexing order at startup would be based on the username (the information "last edited on the server") and the timestamp. In this case the user should be able to select at the client a number of libaries, which should be synced/indexed (based on the information stored at the server) based on the username and timestamp, after this has finished, the indexing is followed on the timestamp without taking care of the user who did the last change.

This solution has the benefit, that the libraries, on which have been worked on that specific computer are synced first. This could be important, because some of our staff works only half a day, so if we would sync libaries only on the server timestamp, this "half-day" computer would sync first the libraries edited by other staff, which works full day, and after this the libaries the half-day-staff on that specific computer works on, because this change was like 4 hours earlier compared to other changes. If we would have a "list" of latest changed libraries on that computer, this computer would change first the libraries which  are worked on that computer and later the other libraries. So for efficiency this would be the best solution.

To shorten up this, I would suggest the following syncing order for libaries:
- Get client-specific information of username and last-edited from the server and index the most recent libraries first changed by that user (user should be able how many libaries should be indexed on that selection based on the username)
- After syncing the selected number of libaries as mentionad above, index all other libraries based on the timestamp (also most recent first) 

I hope, this long writing helps to understand my problem and maybe it helps other people. Because at one point, indexing could not be faster, this would be (as I think) a good solution for such problems.

Additional request:
If it is possible, it would be good, if the icon for non-indexed libaries on the client could be changed, because all libaries have the same "green OK-button", even if they are not indexed. So it would be good to have a icon (for example the green one with a sand glass at the corner), which means that libraries are found on the server and synced on the client, but the user has to wait because they are not indexed (after a restart). Actually I look at the log-file, if one library is indexed or not (if you have more than 100 libraries this makes not much fun...)

Regards and thanks for your great work!
Christian

**Comment by GITchristoph** [comment]
Dear all
for us this got solved after upgrading from server 4.0.6 and client 4.0.6 to server 4.1.2 and client 4.1.6.
The indexing on the same windows machine as explained above and for the exact same folders now takes approx. 3 minutes at startup overall.
Totally acceptable and very workable for us now.

For me this issue can get closed. 

Thanks for solving this,

Chris
