### ISSUE TITLE
Get away from Dropbox

### ISSUE THREAD

**Issue by epe** [haiwen/seafile#1043]
Using seafile since almost 1 year, I've been quite happy so far, but some people keep sending me dropbox download links. 
It allows to download the whole stuff as a zip file, or to integrate it into my own Dropbox, but of course I dislike running that dropbox client for nothing. 

Thinking about how we could help seafile users:

1) The easy workaround: Write a shell script that downloads the zipfile and unzips it in the desired location. 
2) Integrate this feature to the seahub userinterface 
3) Download all the changes in the Dropbox Link (download only).
4) Extra (pro) feature: Connect Dropbox Account with seahub and have the Dropbox Folder as a separate Library with its Folders available as sublibrary.

**Comment by shoeper** [comment]
1-3 is ok, but I'm not sure if it's really needed. You could write it yourself using the seafile api.

And althought I'm not a dev of seafile I don't think 4th point will come because seafile has it's own internal file format and short time before someone wrote a similiar issue requesting to mount local folders or file systems/drives and afaik it got rejected because it would be too much work to make it syncable with the clients.

**Comment by shubhank008** [comment]
1. Is quite easy as there are quite a few dropbox apis to download a shared link, can use that (shell/python/php) to download the file, unzip it and perhaps use the seafile webAPI to upload those files to your seafile instance
2. Currently I myself am looking to improve the seahub interface more, but it being in python is posing a bit problem for me since I am more of a php developer (and server admin), so right now I am deciding whether to hire a python dev to put my instructions to code or redesign a new seahub frontend in php (so users can have option between python and php versions)
3. Not sure what you meant
4. As @shoeper said, doing a virtual directory mount like that is one heck of a time consuming job, and might not even play nicely with seahub. Though there is ofcourse a alternative (atleast in php I can think of), write a dropbox class to sync files from a folder to your dropbox account/folder.
Will just need to run that classCode each 5 mins and then it will read all files present in that "Dropbox" folder (physical folder present on your seafile/server), sync them to dropbox and delete the local instances of the file.

**Comment by freeplant** [comment]
The feature of integrating with Dropbox requires quite a lot time but not interested to many users. So we will not implement it.
