### ISSUE TITLE
seaf-cli missing umask support

### ISSUE THREAD

**Issue by kingfisher77** [haiwen/seafile#1085]
Hi,

mixing seaf-cli with samba-shares is tricky when it comes to access rights of files an directories. We have samba users with umask 0000. seaf-cli has standard linux umask 0022. Samba user don't work with files written from seaf-cli. I did not find a way to modify the umask of seafile. It seems seaf-cli does not honor umask. I tried watcher.py as a workaround but its kind of ugly (because of ~-files).

This issue was already discussed with no result: https://github.com/haiwen/seafile/issues/310

**Comment by denis-b** [comment]
More generally, it would be very interesting to have seaf-cli writing libraries under a different user ( possibly externally mapped to library owner). I wasn't able to find where to change that (maybe a little bit complicated) or simply umask thing. Some guidance into the code would be very appreciated.

**Comment by denis-b** [comment]
the issue will probably be addressed by something like : 
in seafile/lib/utils.c 

 -    return mkdir (path, mode);
 + int ret = 0;
 + mode_t process_mask = umask (0);
 + ret = mkdir (path, mode);
 + umask (process_mask);
 + return ret;

And the same for other functions.

Will try it soon.

**Comment by denis-b** [comment]
This issue and https://github.com/haiwen/seafile/issues/310 are fixed in my branch https://github.com/denis-b/seafile. 
I added support for allowing seaf-daemon to set uid:gid for repos and umask 002 when run as root. The code is not really polished, there are still some problems with repo status,  but it will allow the typical use case of a samba server with libraries on user's shares.

Please test it
