### ISSUE TITLE
400: Bad request when uploading large files

### ISSUE THREAD

**Issue by bartmeuris** [haiwen/seafile#1131]
When I upload rather large files (700Mb ISO's) - I sometimes get a '400' HTTP response back.

I have both problems in the web-interface and in a cli application I'm building. Below is the log of my application.

```
vagrant@precise64:~/seafile-cli$ ./seafile-cli -script scripttest.sea /vagrant/tmp/customubuntu.iso
2015/03/12 13:02:39 # url 'http://########/'
2015/03/12 13:02:39 # user '########'
2015/03/12 13:02:39 # password '********'
2015/03/12 13:02:39 # setlib 'Software'
2015/03/12 13:02:39 # Upload '/vagrant/tmp/customubuntu.iso' => 'Software::/customubuntu.iso'
[DONE] /vagrant/tmp/customubuntu.iso => Software::/customubuntu.iso (Size: 671.00MiB, Time: 31 minutes, 59 seconds, Speed: 358.00KiB/sec)
2015/03/12 13:34:53 [ERROR] Script line 8: 'upload $1': expected return status '200 OK', got '400 Bad Request'
vagrant@precise64:~/seafile-cli$ 
```

When I look in the seafile logfiles, I see only this:

```
[03/12/2015 01:34:52 PM] upload-file.c(392): [upload] No parent dir given.
```

Thing is, I do send a 'parent_dir' as a form field in the HTTP request, it works fine for smaller files I send using exactly the same logic. I tried sending the fields before and after the file data, but it doesn't seem to make a diference.

I first thought it was a problem with my code, but we also have errors with large files when uploading using the web-interface in various browsers (tested: safari, firefox, chrome).

I do run seafile behind an nginx proxy to access seafile on only 1 port, but no errors appear in the nginx logs, and I specifically configured this to avoid problems uploading files:

```
location /seafhttp {
		rewrite ^/seafhttp(.*)$ $1 break;
		proxy_pass http://127.0.0.1:@SEAFILE_FILES_PORT@;
		client_max_body_size 0;
		proxy_connect_timeout  36000s;
		proxy_read_timeout  36000s;
}
```

Any ideas?

**Comment by shubhank008** [comment]
Wild hint but double check the config files for the file size limit as well, I use seafile-server on ubuntu with nginx proxy and can upload 1GB to 7GB files (there are sometimes failed uploads but thats a diff problem)  

Interestingly, the upload itself seems to finish properly but the problem seems to be in post-processing of the upload instead  

ps: my response is for browser and client uploads, not CLI or API

**Comment by makkus** [comment]
I seem to have the same problem. Works well with smaller files, or faster internet connection. So my guess is something related to a timeout, but not really sure.
How would we go about debugging this? I could not see anything relevant in neither nginx nor seafile logs...

**Comment by shoeper** [comment]
Timeouts should get logged by your webserver.

**Comment by bartmeuris** [comment]
@shubhank008: the upload size is not the problem, the entire upload works just fine. The thing is, the upload is a multipart HTTP post, and the `upload_dir` field is the last-one, and somehow it misses it. When I sent the 'small' fields first, it gave the error that there was no file uploaded.

I then added an extra fake multipart field, which fixed most of the issues (but still from time to time I have the problem). I now also upgraded to 4.0.6 - so I don't really know if that was also a part of the fix... I'll have to do some more testing.

**Comment by bartmeuris** [comment]
Also have this in the web interface when uploading (in 4.0.6) - same problem, it gets a 400 Bad Request back from the seafile server after the upload was completed:

![seafile_fail](https://cloud.githubusercontent.com/assets/2588174/6924107/67e0db10-d7d6-11e4-923b-42ab7d456284.png)

**Comment by shoeper** [comment]
Maybe it did exceed the body limit.

**Comment by SuperSpyTX** [comment]
Sorry for necropost, but I ran into this problem recently and found that if you pass the `Content-Length` header with the correct length of the body, the file upload will succeed.  Not passing it can sometimes cause 400s.  I suspect evhttp is trying to calculate the length from the body and stops because of null characters that could exist in the file.

**Comment by SuperSpyTX** [comment]
Sorry for necropost, but I ran into this problem recently with the Upload API and found that if you pass the Content-Length header with the correct length of the body, the file upload will succeed.

Not passing it can cause 400s for certain files that contain null bytes. I suspect evhttp is trying to calculate the length from the body and stops because of said bytes.
