### ISSUE TITLE
Support for OS X 10.6.8

### ISSUE THREAD

**Issue by dakira** [haiwen/seafile#1237]
OS X 10.6.8 is still wildly popular and the most current version you can install on lots of hardware that is still working perfectly good in many offices around the world.

Clients of mine have lots of older generation Mac minis that can only update to 10.6.8 and thus have no option to use Seafile. Same as all the people who still have love for their 2007 Macbooks.

So it would be great if you could look into supporting that version again.

**Comment by simsasaile** [comment]
Hi dakira,

do you need a client version for 10.6 or a server version? Because you postet this issue under seafile, not seafile-client...

If you mean the client, I agree to you, because I'm in the same situation. But I got a lot of help from chilledheard to compile a 32bit OSX10.6 Client which you can download here: https://seacloud.cc/f/dc616acaa2/

But it is only the Client 3.1.3, so it does not support HTTP-sync and the newest server version dropped support for non http-sync...

With homebrew you can also easily compile the mac client on your own: https://github.com/Chilledheart/homebrew-seafile
But again, the last version which is able to run on OSX10.6 is client 3.

**Comment by dakira** [comment]
@simsasaile My bad, I actually wanted to post this issue under seafile-client. Will do that now and close this one. Thanks for all your information!
