### ISSUE TITLE
Directory seafile-data/storage/fs very large

### ISSUE THREAD

**Issue by hongaar** [haiwen/seafile#1309]
After finding I ran out of available inodes on my virtual machine, I found out seafile is using up most of them (using `find / -xdev -printf '%h\n' | sort | uniq -c | sort -k 1 -n`).

I had one large-ish (6GB) library which I just almost completely emptied (for debugging purposes), I set the history setting to __Don't keep history__ and ran `seaf-gc.sh run` multiple times on the server.

This is the output for this library:

`[07/08/15 23:31:30] gc-core.c(350): GC finished. 9 blocks total, about 9 reachable blocks, 0 blocks are removed.`

Which is satisfying, I came from ~90.000 blocks when the library was still full-size.

Still, the `seafile-data/storage/fs/{LIBRARY_ID}/{XX}` directories (258 of them) take up some 1.6GB and ~400.000 inodes (count using `ls -Ria | sed -e 's/^  *//' -e 's/ .*//' -e '/^$/d' -e '/^\./d' | sort -u | wc -l`). 

This is an absurd amount of files for an empty library, is there any way to clean this up?

__EDIT:__ Also, the seaf-cli client has the same problem for the same library.

**Comment by killing** [comment]
You can remove that fs/{library_id} directory if you don't need it any more.

2015-07-09 5:40 GMT+08:00 Joram van den Boezem <notifications@github.com>:

**Comment by hongaar** [comment]
Normally my library isn't empty but contains ~40.000 files worth of ~6GB, so I guess emptying the `fs` dir is not really an option (and also, this could prove a cumbersome manual process on larger seafile deployments)?

**Comment by killing** [comment]
The fs directory contains file system metadata for library. The number of
metadata is roughly the same as you'll have if you store the files in ext4
etc. So I don't think it's a real problem. Do you have a way to enlarge
your file system?

2015-07-09 15:37 GMT+08:00 Joram van den Boezem <notifications@github.com>:

**Comment by hongaar** [comment]
Thanks.

At the moment this is true, the library contains 38308 inodes, the storage/fs 44234 inodes (storage/blocks: 29333). After a while however, storage/fs grew disproportionally large compared to the library size. Also, after deleting all files from the library, storage/fs did not clean up (this might explain the file count creep?)

I'm afraid enlarging the file system will only postpone the problem.

If it matters, the library is a collection of code repositories, with lots of frequently changing/deleted/added files.

**Comment by tzeumer** [comment]
This initial description of this issue is a pretty good match for my current problem, too. I run Seafile under a VPS where the Hoster set the inode limit to 1 Mio. Since I'm only using 14% of my 200 GB it took me quite some time to figure out what's the matter. My 10 GB library uses about 700.000 of the available inodes. Even though it's not that long ago that I ran seaf-gc.sh. 

I wonder, might it be possible to use some kind of container for the Seafile sf so it would'n count against such (low) inode limits?

**Comment by shoeper** [comment]
You could use a loopback device for the fs folder. Not sure how well it'd perform, though.

**Comment by tzeumer** [comment]
Hmm, I "solved" the problem by upgrading to the next higher hosting level with 3 million inodes. Since I've been using my encrypted library for years with nearly about the same size, I don't expect to hit this limit any time soon.

My 10 Euro solution worked and works really well with Seafile. I guess, lots of such hosting offers have similar restrictions, yet are a nice use case for Seafile. So maybe some inbuild solution to reduce the file number in the "fs folder (as I understand it there are just file/folder names) would still be a nice improvement. 

On the other hand, maybe I'm alone in being a bit excessive about using Git and other stuff with lots of small files or limitations like inode limits will become history soon anyway. :)

**Comment by shoeper** [comment]
> My 10 Euro solution worked and works really well with Seafile. I guess, lots of such hosting offers have similar restrictions, yet are a nice use case for Seafile.

I think there are many hosters out with KVM hosting.

> So maybe some inbuild solution to reduce the file number in the "fs folder (as I understand it there are just file/folder names) would still be a nice improvement.

I think this is not very likely, but let's see...

> On the other hand, maybe I'm alone in being a bit excessive about using Git and other stuff with lots of small files or limitations like inode limits will become history soon anyway. :)

This definitely eats inodes.

**Comment by 4ley** [comment]
Hit exactly the same problem, but with seadrive. Are there plans to fix this in future releases?

**Comment by bertvandepoel** [comment]
So for people running into this in more modern times. Seafile server 9.0 has added an extra garbage collection option for "fs" https://manual.seafile.com/maintain/seafile_gc/#removing-fs-objects . Running seaf-gc.sh --rm-fs has reduced fs from 10GB to less than 400MB for me. I hope it helps anyone who stumbles upon this issue!
