### ISSUE TITLE
Uploading big files without desktop client

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile#1320]
Many users are having problems to upload large files without desktop clients (seafdav, seahub, mobile clients, cloud file browser). I think in almost all cases this is caused by timeouts. These are caused because Seafile needs to index data.

I think we cannot ignore this, because many users really want to be able to upload files via seafdav, seahub, mobile clients and cloud file browser.

Here my proposal on how this could get fixed:
1. Put uploaded data in a tmp, but permanent directory (some place where it won't get lost, whatever happens, so not /tmp). Afaik Seafile is already doing this.
2. When upload finishes add it to an indexer queue and return HTTP 200. Furthermore give some message to the user that the file will be processed and appear online after some time (this message could show different time depending on file and queue size).
3. Instead of running the indexer on demand, let it run as service and let the admin define how many indexers he wants to run. Every x seconds and on finished task the indexer checks the queue for new work. On finish the indexer also removes the file from cache and queue. The queue would be an sql table to be persistent. This would make sure that even on crash no files get lost. Seafile would just continue indexing on restart. 
4. for pro edition you could also allow indexer nodes. These could use e.g. SSD storage to speedup indexing.

The advantages would be that all files get securely uploaded, no metter how big they are. And the user wouldn't have to look at the process, he would just see, oh it's up and could be sure it will appear online after some time. Timeouts that can appear when using e.g. seafdav would be gone forever.

**Comment by killing** [comment]
Thanks for your suggestions. But I think your suggested way will degrade the user experience. Asking the user to wait for a uncertain time before the file appears online is not a good experience.

We'd like to find out a better way to reduce the over-all time for uploading and storing a big file on the web. The time can be divided into 3 stages:

1. Browser -> Nginx: the file is uploaded to temp file in Nginx. Nginx store the request into a temp file if gets large.
2. Nginx -> Seafile and indexing: Nginx passes the file to Seafile. Seafile dose the indexing work.
3. Seafile -> storage backend: Seafile stores the blocks to storage backend.

There are a few opportunities to optimize this flow:

1. Improve the indexing algorithm: currently we use Content Defined Chunking (CDC). It requires scanning the file byte-to-byte to divide file into blocks and also calculates the SHA1 for each block. For web uploads we can skip CDC and divide file into fixed size blocks. This will reduce the indexing time in a matter of magnitude, since the CDC implementation is not very fast.
2. Upload big file in blocks, creates pipeline: If the browser divides the file into fixed size blocks before it uploads it to server, we can make stage 1 and stage 2,3 parallel. When the first block is being indexed and saved to backend storage, the second block is being uploaded. This is especially useful in WAN environment, where stage 1 actually takes much longer than stages 2,3 combined. This approach also has an extra benefit that it can support resumable upload. We're going to provide this upload method in the Pro edition.

**Comment by shoeper** [comment]
Have a look at http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_request_buffering
https://www.nginx.com/blog/nginx-1-6-1-7-released/
http://forum.nginx.org/read.php?2,256378,256591#msg-256591
So add `fastcgi_request_buffering off` to nginx to disable request buffering.
Not sure how it works in apache.

I think using that it would be possible that Seafile indexes data while the user is uploading it. This could also solve the problem for WebDAV, where a chunked upload is not possible. And it would remove overhead which is made by nginx when caching large files first. Downside is that one would need to use a recent version of nginx, but I think that is ok.

I've some further questions about this
> Improve the indexing algorithm: currently we use Content Defined Chunking (CDC). It requires scanning the file byte-to-byte to divide file into blocks and also calculates the SHA1 for each block. For web uploads we can skip CDC and divide file into fixed size blocks. This will reduce the indexing time in a matter of magnitude, since the CDC implementation is not very fast.

 * How does it affect the required space? E.g. I upload a 11G file and another one I've added a few bytes at some point (not necessarily at the end of the file).
 * Would it be also possible to use this on client side? I think it would be helpful on mobile clients because currently battery can get drained when adding many files to a synced directory. Moreover some people complain about slow upload - which is caused by the long time required for indexing files.

**Comment by killing** [comment]
Turning off buffering in Nginx will introduce scalability issue in Seafile when there are large amount of clients in the WAN environment. Seafile's http handling is thread based, it doesn't scale well when there are many long-life connections. So this is no option.

My opinion is supporting large file upload in the web browser is not easy, for any cloud storage. That's why all cloud storage have limits on the size of file upload from web. We need some trade-off to make it work. Yes, if we remove CDC from indexing, delta compression is not possible. Users who want that should use the client to sync large files.

**Comment by shoeper** [comment]
If we keep those arguments in mind using a queue wouldn't be the worst solution. It could also allow adding and deleting indexer nodes on the fly which would scale very well.

**Comment by egroeper** [comment]
Will there be any improvements in this matter in the near future?

We had problems with users trying to upload big files, because we ran out of disk space.
After fixing that issues and increasing timeouts in the loadbalancer and for FastCGI, we still get an error notice after Upload has finished (file uploaded completely into `seafile-data/httptemp/`):

![bildschirmfoto_2017-08-29_14-09-43](https://user-images.githubusercontent.com/535113/29872208-da63210a-8d8e-11e7-836d-4a520888140f.png)

It seems like the WebUI shows this error, but the indexing in the background still works and after some time the file appears in the directory it was uploaded to.
So the users get's an error, but the upload works nevertheless. This is worse than telling the user, that the file will be there in a few minutes.

Is there a way to fix this false error? There has to be a timeout somewhere. But where? And Is it configurable?
We set loadbalancer and FastCGI timeout to 15 minutes. This timeout occured earlier.

What is a reasonable file size limit for Seafile web upload? Can we configure in a way, that the user gets a meaningful error message?

**Comment by freeplant** [comment]
We use a third part js code to upload files. It seems we can't change the error code shown easily as last time we tried. Can you try to figure out where the error occur? At the "load balance to  Nginx" or "Nginx to FastCGI"? 

How long does it take to upload 32GB? If it take more than one hour, you should set web_token_expire_time to a larger value (https://manual.seafile.com/config/seafile-conf.html).

**Comment by shoeper** [comment]
Interesting could be whether there is a client timeout. Possibly the client makes the request but doesn't wait for it to finish, closes the connection while reporting back to the user that the upload failed while the indexing is not being cancelled on the server side and finishes in case its done before the server side timeout is being reached.

**Comment by shoeper** [comment]
For uploads above a to be defined size it could be a good idea to use a background service and tell the user that the file is going to appear in a few minutes (let the admin define how many seconds it takes to index 1 gigabyte and calculate an approximate value from that, or even log how long it took to index files and have a look at the average speed from the last 25 uploads).

**Comment by egroeper** [comment]
Sorry for the late reply. Seems like I have a problem with not seeing notifications...

> How long does it take to upload 32GB? If it take more than one hour, you should set web_token_expire_time to a larger value

We were on a local connection. So it didn't take that long. As stated, the upload itself (file reached webserver) took less that 15 minutes. And we are pretty sure, that the timeout is not between loadbalancer and webserver or webserver and fastcgi, because it was earlier than both timeouts:

> We set loadbalancer and FastCGI timeout to 15 minutes. This timeout occured earlier.

btw: We are using Apache as webserver.
