### ISSUE TITLE
AVG Flags ccnet.exe as a virus.

### ISSUE THREAD

**Issue by jsl303** [haiwen/seafile#1339]
I just updated seafile client from 4.2.6 to 4.2.8 on Windows, and Avg flagged ccnet.exe as virus.

**Comment by dbruenig** [comment]
Slightly related to this issue is a problem with Windows Defender which detects false positives in seafile-data directory and moves chunks from there to the quarantine.

I noticed this after upgrading to Windows 10 which enabled Windows Defender automatically, wondering why I had problems with Seafile now.

I disabled online scanning again and also disabled windows defender using gpedit.msc:
Computer Configuration > Administrative Templates > Windows Components > Windows Defender > Turn Off Windows Defender.
