### ISSUE TITLE
seaf-fsck user check too strict/wrong?

### ISSUE THREAD

**Issue by jolbrich** [haiwen/seafile#1361]
After a system failure (full SD card of RasPi I guess), I suffered from a corrupt seafile repository. I was quite happy to learn about seaf-fsck and updated to 4.3. 

My Seafile Data directory is living on an external USB drive (FAT32) that is mounted as `uid=nobody` for $reasons. This stopped me from using seaf-fsck, because in [seaf-fsck.c](https://github.com/haiwen/seafile/blob/master/server/gc/seaf-fsck.c#L65), line 65 and following:
`/* Compare the owner uid of the seafile-data dir with the current uid. */`

I don't think that this is a reasonable check.

**Comment by killing** [comment]
In many cases, users may use a wrong user to run fsck. This can cause the
library inaccessible after that because the seafile server can't access the
new objects created by fsck. This check was added to protect from this case.
But I think you're right. In some cases the users know what they're doing.
A different user may have proper access to the data. We can change this
check into a heads-up and allow the user to confirm what he's doing.

2015-08-31 3:25 GMT+08:00 Jasper Olbrich <notifications@github.com>:
