### ISSUE TITLE
(Windows) 2 Seafile instances for different users on the same machine causes issues

### ISSUE THREAD

**Issue by xarinatan** [haiwen/seafile#1430]
On my Windows 7 64 bit machine I have 2 user accounts; One for work, one for private things.
When Seafile is started up on one of the accounts and I switch to another account, the second Seafile instance seems to fail doing anything. All library icons turn into the orange cloud (not synced), and nothing will sync anymore. The first seafile instance will continue working fine.

This seems like a bug to me, but I haven't had time to setup a testing environment.
Reproduction steps should be:
1) Install Windows with 2 user accounts
2) Install and setup Seafile on both accounts (with 2 different Seafile accounts)
3) Log in to account 1, start seafile, 
4) Switch user (without logging out) to account 2, start seafile there.
5) Seafile instance 2 will fail to do anything. It does connect to the server and show repositories though.

Kind regards, 
Alexander

PS: Great product! Seafile is definitely my favorite personal cloud storage solution by miles on its competitors! Keep up the great work :+1:

**Comment by galvanopus** [comment]
This might be caused by first ccnet.exe instance listening on port TCP 13419. Another ccnet.exe instance can not bind to the same port. You can try to change the port for the second instance in ~/ccnet/ccnet.conf.

```
[Client]
PORT = 13419 
```

**Comment by xarinatan** [comment]
@galvanopus Thanks for the suggestion, but it doesn't appear to help. Instead of showing a 'Downloading 0%' it now shows 'Connecting to server'.

**Comment by xarinatan** [comment]
I can reproduce this across two machines now, and I haven't found any workaround, except for closing the client in one of the accounts (which is very sub optimal;). Can anyone else confirm? Reproduction steps are in the original post.

**Comment by galvanopus** [comment]
I can confirm partially. Here are steps I have performed:

1. Launch Seafile client as admin.
2. Sync test library.
3. Launch Seafile client as user.
4. Sync test library (yep, I was able to sync library).

First I have checked which port ccnet.exe is using and I have wondered. Both ccnet.exe processes were using the same port:

![ccnet](https://cloud.githubusercontent.com/assets/1897495/11016894/8edff440-859f-11e5-9838-ecd860dfe2d0.png)

According to http://stackoverflow.com/questions/1694144/can-two-applications-listen-to-the-same-port two applications can share the same port if using `SO_REUSEADDR`, but I am not sure why ccnet is using it. Which process will accept connection?

Secondly I have checked how many seaf-daemon processes I have. There was only 1 seaf-daemon process, user's ccnet was using admin's seaf-daemon. Can this lead to security issue, @killing?

I suggested that if I launch user client first, I will not be able to sync library as admin, because user's seaf-daemon does not have any rights on admin folder. And this has been confirmed.

So, I guess, that you are not able to sync library as other user, because seaf-daemon has no access to other user's folder.

**Comment by xarinatan** [comment]
@galvanopus Both users are admin on my end.. but it seems a good old reboot fixed my issue, after changing the ports that is. So now both clients will sync! woo :+1: although I do think this should be done automatically by seafile once it detects there's another seafile instance present on the machine (which is something that is easy to make cross platform implementations of I'd reckon). 
Thanks for the workaround!
