### ISSUE TITLE
iOS photo browser doesn't work, iOS thumbnails don't work

### ISSUE THREAD

**Issue by florihupf** [haiwen/seafile#1504]
It only shows white thumbnails with an X in it.

Latest server (on Linux 32 bit 5.x.x). Latest iOS client.

Maybe related: When browsing directories on the iOS app the image thumbnails not really load by themselves.  Sometimes I might see four or so but only if I manually view a picture.

The thumbnails itself are very blurry.

I am surprised that no one else had this issue.  Hmmm...

**Comment by poetwang** [comment]
Is it an encrypted library?

**Comment by florihupf** [comment]
Yes it is.  And i guess it is again something that doesn't work with encrypted libraries. 

I still don't follow the issue with encryption. Clearly the server is capable of unencrypting files (say when you want to download something). Why is that that for convenience and nice things (view pdf or thumbnails or photo browser) this is disabled ?

Especially when the iOS client does it seamless: viewing PDFs for example.  

I could understand it if the clients would decode the files but it doesn't seem it is implemented like this. 

Thanks for explaining!

**Comment by poetwang** [comment]
If the server generates the thumbnails, it will have to cache the thumbnails on the server, this may be unsafe. Now the password only cached on server for 1h, you can also choose the local decryption, then the server may never know the library password. In the next version, iOS client will also support local decryption. So by design, the server will never generate thumbnails for files in encrypted libraries.
