### ISSUE TITLE
Old database backup => client deletes newer files

### ISSUE THREAD

**Issue by fholger** [haiwen/seafile#1533]
So, yesterday I screwed up during a server move and accidentally replaced the Seafile MySQL database with a three months old backup. This effectively reset all libraries to their three months old versions, even though the physical file repository was still up to date. Again, my fault entirely.

However, what happened then is very disconcerting. On several computers, the Seafile client began resetting all synced libraries to the older server version and in the process reverting the local files to older versions and deleting files not present on the server. Thankfully, nothing critical was lost, but the behaviour is the exact opposite of what I would have expected and extremely dangerous. After all, one of the main purposes of syncing files with Seafile is to have multiple backups in case of emergency - yet in this instance a single point of failure erased all of the backups.

The server in question is running Linux and Seafile v5.0.2. The clients are on Windows and at v5.0.4.

**Comment by erenoglu** [comment]
I guess the server nor the clients would have a mechanism to know if you deliberately replaced the files by 3 months old versions or if it was a mistake. 
However, since this is a very exceptional case, maybe developers can implement a safety feature in the client code that if there are big amount of changes pushed by server at once, it could ask the user for interactive confirmation.

**Comment by fholger** [comment]
I don't know how Seafile handles synchronisation, but what I would have expected is that the client sees older files on the server with older timestamps and should thus have uploaded the newer local files to the server instead of the other way around. Local files should not be overwritten or deleted unless that specific file version exists in the Seafile history. If in doubt, it should at least move the local files to a temporary location to allow recovery.

**Comment by killing** [comment]
Seafile doesn't use timestamp for synchronization. It relies on the version history of the library. Because different client's local time can't be synchronized, it's inaccurate to use timestamp for syncing.
Currently I don't know how to provide an automatic safe guard to this unfortunate situation. We'll think about it.

**Comment by fholger** [comment]
I think that's dangerous. If the server has no records in its history about the specific version that the client has, then that version should not be overwritten or deleted (unless I specifically ask the client to), because that can (and did) lead to unrecoverable data loss. As I said, I would have expected that the client instead uploads its version because it differs from any version in the server history and would thus have to be assumed to be a new version?
