### ISSUE TITLE
Don't create directories

### ISSUE THREAD

**Issue by Bodhibear** [haiwen/seafile#156]
Hi!

When I use the last version of Seafile client for Ubuntu and Windows creating directories in the shared folder, the seafile can not sync the information with the seafile server.

Any bug?

Regards,
Juan

**Comment by monkeydri** [comment]
right now empty directories are synced to the server (at least using seadrive) but are not synced back to (another) client.

This is an issue for us because we use empty directories on every new top folder, as a way to enforce content organization, ex :

Library X
- project_1
    - FOLDER_A
    - FOLDER_B
    - FOLDER_C
- project_2
    - FOLDER_A
    - FOLDER_B
    - FOLDER_C
- project_3
    - FOLDER_A
    - FOLDER_B
    - FOLDER_C
...

This way people save files in correct locations.

**More generally this is an issue because it is inconsistent : seafile users to not see the same thing.** User who has created the directoriess does not see the same than other user who has synced them.

Users do not care how files are stored internally and do not know about git, they expect seafile to work like any other sync or drive solution.


A workaround is to put 1 dummy file into each directory but feels hacky + we have to remember it.

---

Seafile server pro 6.3.12
Seadrive 1.0.1 (mac and windows)
