### ISSUE TITLE
[BUG] Can't handle filenames with spaces using web client (browser)

### ISSUE THREAD

**Issue by soakes** [haiwen/seafile#1634]
Hi guys,

I just found a bug using latest version of seafile (Version: 5.1.1) that if you have a file on your server which has spaces in it, then that the file will not open.

It says..  "image cant be found" in the image preview/page. 

However, if you rename it in your desktop client or even the IOS client to replace spaces with underscores then it will then load correctly in the web browser.

I guess your missing the %20 which is required in URLs according to RFC 1738

**Comment by shoeper** [comment]
Please only submit bugs in GitHub issues (Pro customers should contact us via Email).

Feature requests and installation/usage problem should be asked in the forum https://forum.seafile-server.org/.

This is very very likely a configuration issue.

**Comment by soakes** [comment]
My Applogies, I believed it was a bug hence was placed here.

I will tripple check configuration, however, I dont beleive the problem is there and will patch it myself if its required.

**Comment by stalks** [comment]
I'm having the same issue, also with 5.1.1.

Can you shed some light onto what configuration issue this may be? I've just gone through the installation process again and am having the same issue.

> Please only submit bugs in GitHub issues (Pro customers should contact us via Email).
What does this mean? This is GitHub so its in the correct place....?

**Comment by shoeper** [comment]
This is github issue but this is no bug.

See https://app.seafile.de/d/5678a1a321/

**Comment by stalks** [comment]
Awesome, so it works on 5.1.3. Will wait for it to be released, thanks.

> This is github issue but this is no bug.

If something isn't working as expected how do we know if its a bug or not before it is submitted? You should view these reports as a gift from the end-user to better the development of the product. We can't get it right all the time, but we should be allowed to try :)

**Comment by shoeper** [comment]
Nah, it doesn't only work on 5.1.x it does work in all versions I know of. At least for 3.x.x 4.x.x and 5.x.x.

People tend to use Github as a support platform which is not wanted. It was hard work to get the issues clean (It wasn't possible to work on the real bugs because there've been so much noise, before). If one does not know if it's a bug he can ask on the forum. If it is a bug a ticket containing all information  can be opened on github.

Furthermore most "bug reports" are useless. A useful bug reports needs to contain all information on the environment and steps to reproduce. Such a report would be a gift but most of the time the reported "bug" is a configuration issue or does not contain much information, making it hard for the devs to make use of it.

The space topic in specific has been reported multiple times so far. There is even an entry in the manual and searching for it on the forums and on Github should give several results.

**Comment by stalks** [comment]
I found the issue. Seafile 5.x no longer supports the Apache default method of URL encoding and requires an extra line to adjust.

`SetEnvIf Request_URI . proxy-fcgi-pathinfo=unescape`

I've been using the same Apache config with Seafile 2+ for a couple of years. Nice gotcha :)

**Comment by soakes** [comment]
@stalks thanks, this has fixed my issue also.
