### ISSUE TITLE
Issues with spaces in file names/directory names in seahub

### ISSUE THREAD

**Issue by szimszon** [haiwen/seafile#1813]
If you make a directory like "My Photos" in seahub and uploads some images, no thumbnail is generated nor can you preview it. If you rename the directory to "MyPhotos" everything starts to work...

The server is 6.0.7

**Comment by shoeper** [comment]
Are you using Apache webserver?

**Comment by Timsonrobl** [comment]
I just opened this last posted issue among many others closed to discuss this problem.
And to @szimszon : short answer is: Seahub in incompatible with Apache v 2.4.9 - 2.4.11  causing all resources to become inaccessible if they have any character that needs to be URL encoded in their path.

The problem is - Apache 2.4.10 is in current **Debian Stable** release (as for December 2016). Meaning **A LOT** of systems run Apache 2.4.10 this days and we don't know when this will change. And installing Apache from testing Debian branch will make FrankenDebian out of your system pulling php7 packages and whatnot. This effectively means that **"Seafile is not compatible with Debian Jessei's LAMP stack"**. 
Is there truly nothing can be done to mitigate this problem? There is almost nowhere in the Internet people complain about this mod_proxy_fcgi bug other than on Seafile support forums.
Is it impossible to have an option to decode URL internally so there is no need for proxy-fcgi-pathinfo=unescape ? Is there really no solution within Seafile project?

**Comment by Kopertje** [comment]
Hello Szimszon,

I had the same issue, install the following:
apt-get install apache2 subversion libapache2-mod-svn
a2enmod dav_svn
svnadmin create /srv/svn
chown -R www-data: /srv/svn
cat > /etc/apache2/mods-available/dav_svn.conf << EOF
<Location /svn>
DAV svn
SVNPath /srv/svn
>> EOF

Source: https://bugs.launchpad.net/ubuntu/+source/apache2/+bug/1284641
This worked for me.

Greetings,
Robin

**Comment by nonadz** [comment]
I have tried the solution mentioned above from Kopertje, but did not help me out. Still have the same issue. Any other ideas?

Thanks!
