### ISSUE TITLE
sqlite_to_mysql.sh giving errors

### ISSUE THREAD

**Issue by andreasmalta** [haiwen/seafile#1851]
I'm getting many lines of the following:
Error: unknown command or invalid arguments:  "mode"
...and the resulting .sql files are practically empty

I just migrated Seafile successfully from windows to Centos 7, and it's all working OK on sqlite.
But I would like to move DB to MariaDB (10.1), so I'm following instructions on "https://manual.seafile.com/deploy/migrate_from_sqlite_to_mysql.html".
My installation directory is /opt/seafile, and that's where I download and run the script...

**Comment by vmario89** [comment]
the problem is still present because the database model provided by the seafile guideline is from 2016. Since latest versions some database structural things changed. There are missing columns and keys for example. That's why an upgrade is not possible. I wanted to migrate from sqlite to MariaDB. The manual by the way misses the fact that the package sqlite3 (checked on Rasbpian) is required to install to use the sqlite_to_mysql.sh script properly
