### ISSUE TITLE
LDAPS does not work after upgrade from 6.0.7 to 6.0.9

### ISSUE THREAD

**Issue by ghost** [haiwen/seafile#1877]
Hello!

We've performed an upgrade from 6.0.7 to 6.0.9 and now users cannot log in any more and the log shows

`user-mgr.c(281): ldap_bind failed for user cn=seafile,ou=apps,dc=alphabet,dc=com: Can't contact LDAP server.`

When turning off LDAPS and connecting to port 389 it works. However, that's not an option to have transport unsecured.

We're using a certificate signed by Comodo.

EDIT:

Also after the upgrade "about" still show 6.0.7 thought the link is to the 6.0.9 installation (I ran ./minor-upgrade.sh)

**Comment by jh23453** [comment]
Does your system need moving the ldap libraries as described in https://manual.seafile.com/deploy/using_ldap.html (Using TLS connection to LDAP/AD server)?
The is needed after every upgrade for me :-(

**Comment by andreasalberta** [comment]
I'm running centos7 so I also have to remove "libnssutil3.so" from the lib folder.
But recently I also had problems with LDAPS, and in my case it was because of an update to nss (with dependencies) After I rolled back to version 3.21.3-2.el7_3 it started to work again. 
If you are using centos you can use the yum history command to roll back. Now I exclude updates to nss* in the /etc/yum.conf file.
