### ISSUE TITLE
"Do you want to copy the file without properties?" when copying into Seadrive

### ISSUE THREAD

**Issue by Rojetto** [haiwen/seafile#1909]
Sorry if this is the wrong repository, I couldn't find one for the Seadrive client that wasn't specifically for the UI.

I'm mounting my Seafile libraries with Seadrive 0.6.2. When copying files into it, Windows asks if I "want to copy the file without properties" for every single one.

![seadrive_ohneeigenschaften_anon](https://cloud.githubusercontent.com/assets/777285/26800457/ac156e90-4a39-11e7-9103-34783660fde6.png)

**Comment by shoeper** [comment]
Seafile does not support these attributes. I agree that it's not very good that the dialog always occurs, though.

**Comment by Rojetto** [comment]
Okay, thanks for the reply. I'm guessing this is some file metadata that's getting lost, but do you know what exactly?

**Comment by shoeper** [comment]
> do you know what exactly?

E.g. file permissions are not being preserved

**Comment by killing** [comment]
SeaDrive doesn't support extended file attributes and doesn't sync them to the server. Usually extended attributes doesn't contain important information about the file contents. I personally saw this warning when I copy some files from Dropbox to SeaDrive. Dropbox adds extended attributes to the files inside it.
I'm closing this since it doesn't seems to be a bug.

**Comment by Rojetto** [comment]
Wow, you're exactly right about Dropbox. This occured when I was trying to copy my Dropbox stuff into SeaDrive. I just tried a new file that wasn't in my Dropbox before and the warning did not happen.
