### ISSUE TITLE
No seafile-gui in Ubuntu 17.04

### ISSUE THREAD

**Issue by therecluse26** [haiwen/seafile#1922]
Hi, I tried adding your PPA and installing the seafile-gui, but the following error returned:

Package 'seafile-gui' has no installation candidate

**Comment by lins05** [comment]
I tried to enable the builds on launchpad for 17.04 and 17.10, and the builds failed because the 17.04/17.10 by default use python 3, e.g check the logs here: https://code.launchpad.net/~seafile/+archive/ubuntu/seafile-client/+build/12774861

I guess we need to fix the configure.ac script in ccnet/seafile to locate python 2  instead of the default python 3.

**Comment by therecluse26** [comment]
Awesome, I'll try this out tonight, thank you!

**Comment by lins05** [comment]
Yeah, i just tried it on ubuntu 17.04 & 17.10. Both should work now.

**Comment by fuelflo** [comment]
Not working on 17.10. see: #1976
