### ISSUE TITLE
Client still syncing after password change

### ISSUE THREAD

**Issue by HenriWahl** [haiwen/seafile#196]
Is it a  bug or a feature that the client continues to sync a library after the user password has been changed? I would expect the client to ask for the new password in case there is a new password.
Dropbox had a similar behavior (http://dereknewton.com/2011/04/dropbox-authentication-static-host-ids/) which has been considered a security leak.

**Comment by freeplant** [comment]
Fixed in version 4.2.0.

**Comment by hierro** [comment]
Hi all, rcently i discovered one of my pc was connected from google account, since this computer was supposed to be lost by intercontinental expedition, it looks kinda interesting, it was stolen.

I changed password but it will not stop synch, but i really need to know if that computer synched my library, cos all lost luggage story is not clear at all with carrier.

how can read that tokens and know what happened in synch ? thank you very much.

**Comment by freeplant** [comment]
First, support question should be asked in our forum.

If you use the laster version, if you change password, the old tokens are deleted automatically. If you use an old version, you can disconnect the device from the "Devices" tab.
