### ISSUE TITLE
Windows 10 Blink icon on desktop and explorer get 15-17% cpu time

### ISSUE THREAD

**Issue by DrVeider** [haiwen/seafile#1986]
after start seafile client (6.1.1-6.1.3 ) i have blink icon "control panel"(stay on desktop from begining before upgrade from win 8 to win 10 and this is not shortcut), and i see  explorer with 15-20 cpu time in task manager.
time to time  all shortcut on desktop refresh with  x to -> symbol at left down corner.

**Comment by freeplant** [comment]
Can you upload a screenshot?

**Comment by DrVeider** [comment]
https://yadi.sk/i/-kx-8pVU3Pij9b

Like You can see at end of clip - problem end after exit from  seafile client.

**Comment by DrVeider** [comment]
Ok. Just recheck in theme options  visibility for control panel(in last clear it) and clear check box for allowing change  icons  desktop by theme. And no problem now. I think some problem with last options.

**Comment by DrVeider** [comment]
look like this problem -
https://answers.microsoft.com/en-us/windows/forum/windows_10-security/all-control-panel-items-icon-on-desktop/451fdea0-2483-485f-ac63-e1a92d4dff9e

**Comment by Riffer** [comment]
Has anyone a fix for the problem? Same issue like DrVeider here on Windows 10.

Already tried to remove 'suspicios' registry entries but without help. Have this problem on other Windows 10 systems too. Afaik it happend first time after using a desktop folder as a Seafile folder. Since then not only "control panel" returns blinking but all icons on the desktop have a "X" or Checkmark on them (as if they are controlled by seafile).

**Comment by hugoAAAAA** [comment]
is not a real solution,
but i solve the problem by disabling "explorer extention" in seafile basic parameters.
but after you can't see seafile icon on your sync folder
