### ISSUE TITLE
seafile-ignore.txt, how to use with individually synced folders?

### ISSUE THREAD

**Issue by Jickelsen** [haiwen/seafile#2080]
Hi
My situation is that I am using Seafile to sync a large number of source code folders between computers. For this it is important that e.g. node_modules is kept from syncing, as it is full of small files and changes often. For this I am using a seafile-ignore.txt file in the root of the source code library. 

However one of the computers I am syncing to (the target machine) does not need/have room for all the source code folders, so for this I am using the Cloud File Browser in the Seafile Client to sync individual folders.

The problem that arises is that individually synced folders on the target machine the do not seem to respect the seafile-ignore.txt rules at the root of the library. A problem this causes in normal use is that when I start working and run npm install a node_modules folder will be created that is then synced up to the cloud, which is what I want to avoid.

I have tried adding a seafile-ignore.txt at the root of the synced folder but this seems to be ignored by the Seafile Client. 

How do I go about this? Without being able to ignore folders and files by name I cannot continue using Seafile.

**Comment by freeplant** [comment]
Please ask support questions in our forum https://forum.seafile.com

**Comment by retani** [comment]
The point of this issue is that **seafile-ignore.txt is ignored for selectively synced subfolders.** There does not seem to be a solution yet (I checked the forum).

I have the same problem as my library is a collection of projects, some of them have node_modules folder which hold huge number of temporary files (breaking seafile sync).

```
# seafile-ignore.txt
*/node_modules/
```

When syncing the whole library, this ignore pattern works as intended. None of the node_modules folders are synced. But when selectively syncing just some of the project folders on the top level of the library, it does not work and all node_modules folders are synced again. I could not find this behavior documented anywhere.

### Here are some ideas
- Document this behaviour in https://help.seafile.com/en/syncing_client/excluding_files.html
- Make seafile-ignore.txt work when subfolders of a library are synched
- Allow seafile-ignore.txt for subfolders (similar to nesting .gitignore files), so I could add individual ignore patterns to a subfolder that becomes the root folder of a selective sync
