### ISSUE TITLE
clone.db leaks passwords of encrypted libraries....in plain text

### ISSUE THREAD

**Issue by RoestVrijStaal** [haiwen/seafile#2088]
Steps to reproduce:
1. Open `<directory where you picked to put your Seafile folder there>/Seafile/.seafile-data/clone.db` with your favourite text editor which isn't picky or a hex viewer,
2. Search on your account name to find your passwords next to it, or search on parts of your password.
3. Call an ambulance for the heart attack you've unlocked by doing step 2.

The fishy part is when opening _clone.db_ with a database tool like "[DB Browser for SQLite](https://github.com/sqlitebrowser/sqlitebrowser)", none of that data is seen during browsing trough the database with that tool. 

I know implementing methods to "keep the app know" the passwords could be tricky, but is this intentional?

Affected OS: Windows 7 x64
SeaFile: v6.1.8

**Comment by egroeper** [comment]
> The fishy part is when opening clone.db with a database tool like "DB Browser for SQLite", none of that data is seen during browsing trough the database with that tool.

Possible root cause for this, is that you see deleted db entries with your text editor. Those are not show by your sqlite tool. Deleted entries are only removed from the database file, when vacuum is done on the file (file gets rebuild).

Looking at my clone.db I can't see my account or password. I assume the information is stored for cloning and removed afterwards. The question is if and when vacuum is run on the database file.

**Comment by shoeper** [comment]
Although this looks like the password does not need to be stored there the client needs to be trusted as it contains the password anyway.

The password also is cached on the server when using seahub (otherwise the web functionality would not work), so using a password that is used for other services as well is not recommended.

This is a seafile-client issue and should be moved to the seafile-client issue tracker.

**Comment by shoeper** [comment]
https://github.com/haiwen/seafile-client/issues/1122
