### ISSUE TITLE
autorun failed:failed to run "ccnet-server -t"

### ISSUE THREAD

**Issue by YuSetsuna** [haiwen/seafile#2107]
systemctl log like this:
> Sep 30 21:21:12 arch systemd[1]: Starting Seafile...
Sep 30 21:21:16 arch seafile.sh[303]: failed to run "ccnet-server -t"
Sep 30 21:21:16 arch seafile.sh[303]: [09/30/18 21:21:15] ../common/session.c(132): using config file /home/seafile/conf/cc>
Sep 30 21:21:16 arch seafile.sh[303]: [09/30/18 21:21:15] ../common/ccnet-db.c(124): Failed to get database connection: Fai>
Sep 30 21:21:16 arch seafile.sh[303]: [09/30/18 21:21:15] user-mgr.c(769): Failed to create user db tables.
Sep 30 21:21:16 arch systemd[1]: seafile.service: Main process exited, code=exited, status=1/FAILURE
Sep 30 21:21:16 arch systemd[1]: seafile.service: Failed with result 'exit-code'.
Sep 30 21:21:16 arch systemd[1]: Failed to start Seafile.

**Comment by YuSetsuna** [comment]
but after I restart it ,it works as expectation.

**Comment by shoeper** [comment]
Looks likes it starts before your sql server does.

**Comment by adrian-leu** [comment]
I have exactly the same problem. Did somebody find a solution to start seafile and seahub after the sql server?

**Comment by adrian-leu** [comment]
I have exactly the same problem. Did anybody find a solution to start seafile and seahub after the sql server?

**Comment by shoeper** [comment]
Add a service (for systemd or what you use) and let it depend on your sql service.

**Comment by adrian-leu** [comment]
Thanks for the quick reply! I figured out that I needed a dependency, but I did not know how to create it. I followed the official instructions to set up the service and then I got the error that was mentioned at the beginning of this thread: https://manual.seafile.com/deploy/start_seafile_at_system_bootup.html

In meanwhile I found out that I also had to add this line to the services in order to create the right ordering:
After=mysql.service

As found here:
https://unix.stackexchange.com/questions/43202/how-can-i-start-a-systemd-service-only-after-mysql-has-started

Now it works!
