### ISSUE TITLE
Selective sync

### ISSUE THREAD

**Issue by UgoM** [haiwen/seafile#239]
This is a feature which is missing.

It would be nice if we could syncronize only a few folders/files in a library.

For example, I have a big library (like 10Gb), and I want to work only on files in a specific folder without downloading the entire library. Currently, I need to download the folder and then re-upload each file I modified throught the web interface.
Another thing I could do would be to split my big library in multiple tiny library. But I don't want to for other reasons.

**Comment by darkdragon-001** [comment]
+1

Would be nice to have it combined with Linux fuse / Windows virtual drive as some sort of caching mechanism similar to [windows offline files][1] or or [linux offlinefs][2].

[1]: http://windows.microsoft.com/en-us/windows/understanding-offline-files
[2]: https://github.com/darkdragon-001/offlinefs

**Comment by tomchiverton** [comment]
+1

**Comment by teoxrr** [comment]
+1

**Comment by arnova** [comment]
Selective sync is actually the only function we're missing here at the moment. We use a SeaFile library containg folders for all our projects, where it would be really nice if you could just sync one of those project-folders.

**Comment by Sylox** [comment]
:+1:

**Comment by freeplant** [comment]
The selective sync has been added in pro edition 4.1:

![qq20150418-1 2x](https://cloud.githubusercontent.com/assets/109339/7367305/120ecb46-edd1-11e4-92c0-8216aad412b2.png)

**Comment by arnova** [comment]
A real pity this feature won't be made available to ordinary users :/

**Comment by fr500** [comment]
yeah it seems so awkward... if only pro-free was a bit more open, at least 5 users or something..

**Comment by synthead** [comment]
The fact that this is not in the open source version is why I am not using Seafile. This is a rudimentary feature.

**Comment by niij** [comment]
It appears that selective sub sync is now available for the [community version](https://www.seafile.com/en/product/private_server/).  But it behaves in a confusing manner where the selective folders are synced to the ROOT of the seafile directory, instead of the directory tree being built out to the selected folders.  Basically what @seanmadsen was talking about earlier in this thread.  Dropbox and Onedrive build out the directory structure correctly, if a reference is helpful.

If you have the below directory structure and want to only sync the 2015 files you will have 2015Tax and 2015Audit in your seafile/ root directory.
- seafile/
  - Taxes/
    - 2014Tax/
    - **2015Tax/**
  - Auditing/
    - 2014Audit/
    - **2015Audit/**



Current behavior when syncing 2015Tax and 2015Audit is:
- seafile/
  - 2015Tax/
  - 2015Audit/

Expected behavior:
- seafile/
  - Taxes/
    - 2015Tax/
  - Auditing/
    - 2015Audit/

**Comment by fr500** [comment]
the folders sync to whatever folder you want, you can sync them to other
drive if you want.
You can't have the same functionality as dropbox because there is no single
top level dir in seafile.

**Comment by tomchiverton** [comment]
On Tuesday, 7 November 2017 03:32:02 GMT Andrés wrote:
> the folders sync to whatever folder you want, you can sync them to other
> drive if you want.
> You can't have the same functionality as dropbox because there is no single
> top level dir in seafile.

Sure there is. It's presented this way in the GUI, with top level folders being libraries.

So I might have in Seafile

My Library/foo/bar
Shared Library/baz/boo

If I selectively sync bar and boo to a local folder, I should end up with

/some/local/folder/My Library/foo/bar
/some/local/folder/Shared Library/baz/boo

-- 
Tom
Say a prayer for the dying; say half a prayer for the agnostics.
