### ISSUE TITLE
Limit history by number of revisions

### ISSUE THREAD

**Issue by wdamien** [haiwen/seafile#240]
I use the day limit for history, but it would ne nice to be-able to limit by number of revisions instead of days (as an option). This is mainly to keep down on the file size of the Seafile instance, and sometimes we don't need to go back 2 weeks in history, and all we would need is the past X revisions.

**Comment by andreapx** [comment]
I can't see this feature in the last release.
Are you planning to add it?
Thanks!
Andrea

**Comment by freeplant** [comment]
We don't have a plan to implement it yet.

**Comment by andreapx** [comment]
Ok

**Comment by bug** [comment]
@freeplant If I understand correctly, the latest HEAD commit of master the server transfers to the client is valid if its timestamp is more than now() - keep_days (in seconds). Right? Suppose keep_days=10. What happens if a client deletes a file on day 11? There is no (valid) previous revision anymore for this file (no commit on master fresh enough to be valid) and so if the deletion is by error the file is simply lost?

**Comment by freeplant** [comment]
This feature will not be implemented.
