### ISSUE TITLE
Client complains about "symbols that are not supported by the Windows system". I don't have Windows.

### ISSUE THREAD

**Issue by deanishe** [haiwen/seafile#2451]
My Mac client (8.0.2) is throwing errors over filepaths that aren't supported by Windows.

I don't use Windows. How do I turn these pointless errors off?

**Comment by feiniks** [comment]
Hi,this sync error is because you are creating files or directories with illegal characters which cannot be synced on Windows. Mac or Linux can sync them normally, but windows can't.

**Comment by deanishe** [comment]
I understand what the error message is saying. I don’t care because I don’t use Windows.

Now I have a bunch of folders showing sync errors, except they’re not real errors because there’s no Windows.

If a real error occurs, how am I supposed to notice among the hundreds of bogus error messages Seafile is showing me?

**Comment by hg2s** [comment]
I noticed this a few days ago and it sent me scrambling for a terminal command to rename offending files. Really ruined my morning! 

Yesterday, a client laptop came online and flagged the same error! This is where the real headache begins. The local store of files on the laptop were in error even though the server was previously sanitized for illegal symbols. Oh, dear. 

I yanked the libraries from the laptop and did a re-sync. All's well but very disruptive. And this broad-brush approach will not work in every case, I suspect. 

I don't think the Mac users are going to be very receptive to this new feature. Should this feature be a check box in the desktop client Preferences to _warn_ about files (and folders) that use illegal characters?

**Comment by DPTJKKVH** [comment]
Dear Seafile team. I greatly respect your work and I am thankful for your contributions to open source and a decentralized Internet.

Everyone that is connected to my Seafile server, including myself, is using Linux exclusively on their desktop and laptop computers. 

I do understand that you want to offer servers that have a mixed OS userbase the option to warn about incompatible symbols. I can even understand if you want this warning to be enabled by default.

However you must give server admins the option to disable those warnings. There is no reason to assume that every server is exposed to windows clients. Even at my workplace we have replaced all Windows machines with Linux clients.

For servers with no Windows users this warning is not only unnecessary but harmful because it confuses, scares and annoys users greatly and it distracts from real errors. People will stop reporting real errors to me if they are exposed to false errors all the time.

Dear Seafile Team please give admins a server wide option to disable the windows symbol error. This is very important!

**Comment by Redsandro** [comment]
I wanted to open a new issue until community member **TheNomad11** pointed me to this one.

### Seafile 8.0.2 introduces breaking change by enforcing Windows compatibility

I'm running Linux (Mint and Ubuntu). Both my home and office Desktop auto-updated to Seafile 8.0.2. I'm getting a lot of errors from the files resulting in exclamation marks and sync problems with almost all my libraries. This includes the most basic files. For example:

> File path contains symbols that are not supported by the Windows system:
> "~/Documents/Scans & Docs/Scan 20210526_111633.pdf”
>
> File path contains symbols that are not supported by the Windows system:
> "~/Pictures/Screenshot from 2021-05-27 13:45:30.png”

On a Linux system, certain things generate files that are incompatible with Windows (because why should they) all the time. For example: User makes screenshots. They are automatically stored with the time in the filename i.e. a colon. I don’t think the user is meant to manually rename every screenshot, unless they explicitly indicate Windows compatibility is relevant for and important to them. 

I do not have a Windows machine and I do not care about compatibility. This certainly shouldn’t have been a breaking change _in a patch release_ (from 8.0.1 to 8.0.2), but rather something to enable for new libraries, something to opt-in, or something for a major release.

Are my files save or not? Are they synced or not? If I can’t get rid of all these permanent exclamation marks with sync error messages for this previously fine implementation, I don't feel particularly safe.

I wanted to downgrade. Can I technically revert to 801 without a footgun (e.g. “this database is for a newer version” type messages)? Doesn't really matter, since the previous version 8.0.1 doesn't seem to be available from the package manager anymore:

![image](https://user-images.githubusercontent.com/1702193/120116883-a43c6080-c18a-11eb-9a23-5e7be0462c6a.png)

In my opinion, an update should never break your well running system like that. I don't really have the patience to see what happens. Personally I'm in the process of migrating my most pressing libraries to Syncthing, which I have been running in tandem with Seafile for a while. But I'm hoping this will be rolled back in a 8.0.3 hotfix **real soon** so I don't have to migrate the other users on this system. People don't like change.

**Comment by DPTJKKVH** [comment]
While this behavior was intruduced with a client change, there is plenty reason to allow server admins to supress those errors when those "symbols" are encountered in libraries hosted on their own servers.

This way users with multiple accounts on different server can have the warning activated for their "Windows servers" while not being bothered on the Linux only servers libraries.

**Comment by bertvandepoel** [comment]
If I understand things correctly, this is only a client bug/issue. In 8.0.2, a new check was added in the seafile-client code. It's been reported on the appropriate project several times: 
https://github.com/haiwen/seafile-client/issues/1359
https://github.com/haiwen/seafile-client/issues/1360
https://github.com/haiwen/seafile-client/issues/1362

We're hoping to receive word from the devs/maintainers and based on that someone from the community might be able to write a pull request to fix this, if the maintainers don't chose to do so theirselves of course.

Just so you guys know what the status is and where this issue originates from. Fingers crossed that it can be fixed soon, since the notifications are quite annoying indeed.

**Comment by unDocUMeantIt** [comment]
> Yesterday, a client laptop came online and flagged the same error! This is where the real headache begins. The local store of files on the laptop were in error even though the server was previously sanitized for illegal symbols. Oh, dear.
> 
> I yanked the libraries from the laptop and did a re-sync. All's well but very disruptive.

i am having a similar problem, except removing the library and re-syncing it didn't help. the file in question is long since renamed, but i am still getting the error message about that file that no longer exists. i have no idea how to fix this, the library is currently useless.

**Comment by hg2s** [comment]
> i am having a similar problem, except removing the library and re-syncing it didn't help. the file in question is long since renamed, but i am still getting the error message about that file that no longer exists. i have no idea how to fix this, the library is currently useless.

Try this: quit the Seafile client, backup/rename the directory .seafile-data, launch the client and re-sync the library(s).

**Comment by DPTJKKVH** [comment]
@killing you merged the commit that produces those errors. Please revert the merge until the commit includes an option to disable Windows compatibility errors.

**Comment by unDocUMeantIt** [comment]
> Try this: quit the Seafile client, backup/rename the directory .seafile-data, launch the client and re-sync the library(s).

hm, i have three different servers configured and dozens of libraries from each are synced, some have 200-300 GB of data. it seems a bit out of scope to resync all of these libraries when only one is failing because the client has a bug. i'd rather fix the cache or db that's causing this.

**Comment by killing** [comment]
We'll add an option in 8.0.3 version on the client to disable these notifications. For now you may downgrade to 8.0.1 version.

**Comment by DPTJKKVH** [comment]
Hello @killing . Thank you for confirming the option to toggle warnings in 8.0.3. Looking forward to it! I appreciate the quick reply and consideration. 👍

**Comment by TheNomad11** [comment]
> We'll add an option in 8.0.3 version on the client to disable these notifications. For now you may downgrade to 8.0.1 version.

Great. How can I downgrade the Linux client? I am on Linux Mint

**Comment by bertvandepoel** [comment]
@TheNomad11 I don't know the GUI way to do it, since I tend to use the command line a lot, but it seems the Seafile team has downgraded their apt repos all the 8.0.1 again (apt is relevant for all Ubuntu flavours, Debian, Mint, and other Debian/Ubuntu derivatives). You simply `sudo apt update` then followed by `sudo apt install seafile-gui=8.0.1 seafile-daemon=8.0.1` to make apt downgrade the packages.

Thanks @killing for taking on this task and for making the downgrade available. It's greatly appreciated!

**Comment by killing** [comment]
We have now downgraded the official Linux sources to 8.0.1. You may uninstall Seafile and re-install. That should have 8.0.1 installed.

**Comment by Redsandro** [comment]
> How can I downgrade the Linux client? I am on Linux Mint

After updating your sources in Synaptic, choose Package -> "Force Version" (Ctrl + E) for each of the Seafile packages.

![image](https://user-images.githubusercontent.com/1702193/120313936-f5f40080-c2da-11eb-8bbe-2a6994d96259.png)

You need to do this in a specific order (from bottom to top) otherwise Synaptic will want to remove packages first.

Please note that you need to manually release the forced version once 8.0.3 update comes out.

**Comment by TheNomad11** [comment]
> @TheNomad11 You simply `sudo apt update` then followed by `sudo apt install seafile-gui=8.0.1 seafile-daemon=8.0.1` to make apt downgrade the packages.

Thanks a lot @bertvandepoel Your solution works perfectly. No need to uninstall anything, @killing

**Comment by ivo-s** [comment]
There seems to be another underlying problem. When I remove the flagged files, everything works fine until another Windows client makes a change in the Seafile library. The change can be unrelated to the files, as long as it is done on a Windows machine and inside the library in question. The deleted files are then brought back as if they were never deleted, and the error reoccurs. This might be related to what @unDocUMeantIt was describing.

@killing If I just silence these errors on the client side, wouldn't there still remain the problem of the files not being deletable? The problem might be that the files are somehow tracked by Windows clients, even though they are not synced to the local folder. Is there a more graceful solution than forcing every Windows user to delete `.seafile-data` and manually resync everything?

**Comment by DPTJKKVH** [comment]
@ivo-s If you look at the pull request that shows the errors you will see that it does just that: Show an error.

It does in no way change anything on your files or the names and it does not restore them or anything else.

So the sync issues you and some other people are experiencing are not related to the error messages produced and thus not related to this issue/ticked. I suggest to open a separate issue instead.

I'm on version 8.0.2, a version that has the symbol error notifications not implemented, and I as well noticed that some files, especially large ones, do not get picked up as changed by the server/client when locally deleted. I do have to manually trigger a sync to pick those changes up. So there is a sync issue in the client, especially concerning deleted files, that is unrelated to the symbol error notice.

As I said: A new ticked/issue should be opened and it should be in the sync client repo, not the server repo, if you consider this an issue worth debugging. Thanks.

**Comment by unDocUMeantIt** [comment]
just for the record: i didn't have an issue with reappearing files. changing the file's name just didn't make the error message go away. the file itself was correctly synced on all machines.

**Comment by cupcakearmy** [comment]
> We'll add an option in 8.0.3 version on the client to disable these notifications. For now you may downgrade to 8.0.1 version.

Please! I've seing notifications each second the last 24h 😅 had to disable them. (macOS, 8.0.2)

**Comment by DPTJKKVH** [comment]
Has the lord cursed you with blindness? You have to downgrade to 8.0.1 like you quoted yourself.

**Comment by cupcakearmy** [comment]
> Has the lord cursed you with blindness? You have to downgrade to 8.0.1 like you quoted yourself.

😅😅 Yes I saw that, but I'll simply wait for 8.0.3 with notifications turned off :)

**Comment by YamashitaRen** [comment]
> We'll add an option in 8.0.3 version on the client to disable these notifications. For now you may downgrade to 8.0.1 version.

Hello. You forgot to remove the warning too.
![warning 1](https://user-images.githubusercontent.com/4103637/123660954-689dc080-d834-11eb-8dfe-20c035906496.png)
![Warning 2](https://user-images.githubusercontent.com/4103637/123660968-6b98b100-d834-11eb-9386-c3c052da74c0.png)

**Comment by Jasper-Ben** [comment]
> Hello. You forgot to remove the warning too.

Can confirm this behavior. The notifications are gone, however the warning within the client is still there.

**Comment by trap000d** [comment]
https://github.com/haiwen/seafile-client/commit/6b912e878d5d239a2231d503e6f9e20c7c8a418d#r52853394

**Comment by unDocUMeantIt** [comment]
> changing the file's name just didn't make the error message go away.

i have now upgraded to 8.0.3 but this issue is still not fixed. there is exactly one file the seafile client complains about, and it doesn't even matter if i remove the whole subdirectory with it from the library -- the error message reappears with the next sync, allthough the file is not there any more.

i ran a full seaf_fsck on the server, didn't find anything. but it's not just me having the problem, it is also bugging persons i shared the library with (after they upgraded to 8.0.3, that is, they skipped 8.0.2 because of theses issues). please tell me how i can fix this.

**Comment by unDocUMeantIt** [comment]
> 3. Implement file names check ONLY in Windows version of daemon/client - I assume the problem is in Windows file system limitations, so why Apple and Linux users should suffer?

i think that's a wrong approach. the underlying problem this feature is trying to address is that unix filesystems are ok with file names that cause problems on windows filesystems. it is unlikely to produce those errors running windows, but likely that windows users are affected when linux/macOS users share files with problematic names. running these checks only on windows installations is therefore pointless.

actually, i can see why this can be a useful feature, as i use seafile in settings where users with various operating systems are sharing libraries with each other, so it's good to have all clients check whether file name are likely to cause problems on ther user's computers. it's also good to have an option to disable it if you know what you are doing.

i actually would like to use it -- i just don't want it to frell up my local database beyond repair.

**Comment by bertvandepoel** [comment]
I've just upgraded to 8.0.3 through my package manager. Of course initially the notifications were back, but after enabling the setting "Hide Windows incompatibility paths Message", everything is perfectly fine now!

@unDocUMeantIt not sure what exactly is wrong on your end. I'm afraid it works fine here.

**Comment by unDocUMeantIt** [comment]
> @unDocUMeantIt not sure what exactly is wrong on your end. I'm afraid it works fine here.

well, but you said you deactivated the messages? that's no a solution to my issue, it would just hide it. i wouldn't classify that as "working fine" ;)

i don't have a problem with renaming files. i simply can't rename what is not there any longer because it was previously renamed and then deleted.

**Comment by bertvandepoel** [comment]
@unDocUMeantIt that sounds like a completely separate issue then. I would suggest filing a new bug on GitHub then. This bug is about receiving notifications about actual files using filenames that are incompatible with Windows by people who just use Linux or Mac and therefore want to disable those notifications. It sounds like your problem is different, and you therefore have a better chance of getting it looked into and fixed as a separate issue. This issue will almost certainly get closed by @killing (or another Seafile/Haiwen member) once enough people have confirmed their notifications are gone after enabling the new setting, as is fairly standard with these kinds of FOSS projects.

**Comment by unDocUMeantIt** [comment]
> This issue will almost certainly get closed by @killing (or another Seafile/Haiwen member) once enough people have confirmed their notifications are gone after enabling the new setting, as is fairly standard with these kinds of FOSS projects.

sure, i'll gladly open a new issue. this whole ticket thread was kind of misplaced in the first place, filed under server when it actually affected the clients ;)

**Comment by cupcakearmy** [comment]
Upgraded to 8.0.3 (macOS) but still the notification tray gets flooded after checking "hide windows compatibility"

**Comment by YamashitaRen** [comment]
> I've just upgraded to 8.0.3 through my package manager. Of course initially the notifications were back, but after enabling the setting "Hide Windows incompatibility paths Message", everything is perfectly fine now!
> 
> @unDocUMeantIt not sure what exactly is wrong on your end. I'm afraid it works fine here.

No. It does not.
https://github.com/haiwen/seafile/issues/2451#issuecomment-869771615

**Comment by bertvandepoel** [comment]
@cupcakearmy Did you go to settings and tick the checkbox before "Hide Windows incompatibility paths Message"? You need to do that before it hides the notifications!

**Comment by Jasper-Ben** [comment]
> @cupcakearmy Did you go to settings and tick the checkbox before "Hide Windows incompatibility paths Message"? You need to do that before it hides the notifications!

Yes, the checkbox is ticked. And the popup notifications are gone. However, the warning/error/whatever in the client remains, as seen in comment https://github.com/haiwen/seafile/issues/2451#issuecomment-869771615

**Comment by cupcakearmy** [comment]
> @cupcakearmy Did you go to settings and tick the checkbox before "Hide Windows incompatibility paths Message"? You need to do that before it hides the notifications!

Yes, also restarted the client

**Comment by trap000d** [comment]
> 3 is no good because the whole point of this commit is to make the life of not-Windows users terrible so Windows users will not have to suffer through unsupported symbols issues.
Indeed, Windows users have already suffered enough :)

**Comment by trap000d** [comment]
> > 1. Implement file names check ONLY in Windows version of daemon/client - I assume the problem is in Windows file system limitations, so why Apple and Linux users should suffer?
> 
> i think that's a wrong approach. the underlying problem this feature is trying to address is that unix filesystems are ok with file names that cause problems on windows filesystems. it is unlikely to produce those errors running windows, but likely that windows users are affected when linux/macOS users share files with problematic names. running these checks only on windows installations is therefore pointless.

I think you think wrong that's a wrong approach. "My IMHO is stronger than your IMHO" - is a weak argument, though.
So here my point of view.
1. Seafile server is name agnostic - client can upload and download any file with any name (I've not tried a ``` "Robert'); DROP TABLE Students;-- ```, though)
2. There are many platforms and file systems with various limitations, e.g. case-sensitive/insensitive in MacOS, different reserved names in Windows/MacOS/Linux/BSD, different Unicode standards supported by O/Ses.
3. Sync process for any new file can be represented as 4 major steps:
- Create local file on one client
- Upload file to server
- Download file from server on other client
- Save file as local
4. The only place where error may appear is the last step. 

My point is: the name validation on upload is useless - if local file exists and can be opened with a standard system file API, the name is valid. Dot. Period. If you want to catch the invalid file names, it's better to do it on download -> try to save -> catch oops, invalid name -> do something (*). 
Otherwise the next step would be to disable case in file names (because Apple users have troubles), then emoji and Unicode (because of Windows UTF-8/UTF-16 miscompatibility) and finally left with upper case ASCII7 only (EBCDIC users will suffer, though).

As for "do something"
The best for me would be to automatically rename invalid name in client with web escape symbols (like browsers). Optionally client might throw a warning like "invalid name - file '$&:.txt' has been renamed to %24%26%3a.txt"

**Comment by unDocUMeantIt** [comment]
> * Create local file on one client
> * Upload file to server
> * Download file from server on other client
> * Save file as local
> 
> 1. The only place where error may appear is the last step.

let's look at two different use cases:

1. i use my seafile server only for myself (e.g., syncing data between devices)

    for this usecase only checking file names during download might be an idea to consider, because it will either never happen or at least i'm still in control of my file names. in the latter case, however, it would also not make much of a difference if the check was done during upload, as it is always me who has to take care of it at some point.

2. i use my seafile server to share data with other users

    in cases where i share a problematically named file with others, you are suggesting the receiver should rename the file or even the client could do it automatically. i'm assuming the file name change would also affect my local files, otherwise you'd have two different files. firstly, this would be impossible with libraries you want to share read-only; especially if the source file system is mounted read-only also (i actually do that). secondly, i would like to be the first to decide how to name my files, especially if it's not simply a single file but one that is supposed to be included or accessed by scripts or other processes. i would like to be aware of those changes, so i can also adjust the respective scripts/processes. thirdly, if problematic file names would only be bugging receivers, i would probably try to revert to the old, problemtic name, or keep naming new files in problematic ways, only to see them "magically" change shortly after, until i get like a call from someone asking me to leave my files alone. therefore, if any other user can have a problem with a file name, all clients should tell. that should be done even without any other known users, they might only be added at a later time, i wouldn't want to suddenly have to rename a bunch of files then.

so from my view this feature only makes sense if it's actually bugging everyone to stick to proper file names, and if you don't want that you should be able to deactivate it completely, at the risk of not being able to share content with other users.

**Comment by cupcakearmy** [comment]
> > @cupcakearmy Did you go to settings and tick the checkbox before "Hide Windows incompatibility paths Message"? You need to do that before it hides the notifications!
> 
> Yes, also restarted the client

@Jasper-Ben After deleting local logs and restarting again it seems to work fine. Not sure if deleting the logs was the solution or just restarting a few times.

**Comment by trap000d** [comment]
> > * Create local file on one client
> > * Upload file to server
> > * Download file from server on other client
> > * Save file as local
> > 
> > 
> > 1. The only place where error may appear is the last step.
> 
> let's look at two different use cases:
> 
>     1. i use my seafile server only for myself (e.g., syncing data between devices)
>        for this usecase only checking file names during download might be an idea to consider, because it will either never happen or at least i'm still in control of my file names. in the latter case, however, it would also not make much of a difference if the check was done during upload, as it is always me who has to take care of it at some point.

OK. Then my question is: why Windows namespace was chosen? Basically it's not a subset of MacOS/Linux (they actually form three overlapping sets) so the problem may appear between Windows->Linux as well as Windows->MacOS, or MacOS->Linux. Do you plan to validate names in these cases? I suppose, if you want to avoid any problems with names, you have to allow only names from subset of ALL supported namespaces.

Few more words/complains.
a) from system administrator
This "feature" introduces extra annoyance only for users due to broken UX. In my particular case I've got my own little server at home with 5 devices and 3 users and ~20GB of data on storage; and another server at work with ~20 users, ~20-40 devices, and ~200GB of data. There are no Windows clients at all - we have running Linux everywhere. I expect that after eventual update I'll start receiving calls from these users about errors in client. 

b) from ordinary Linux user
I'm keeping a relatively small number of files in my Seafile folder:
```
~/Seafile$ ls -R | wc -l
7457
```
About 10-20 of them have "winvalid" names (honestly, I have no idea how many). Do you have any idea of how to find them fast and "fix" names? E.g. provide a regex for find/awk? Please don't mention manual rename - numbers CAN be e.g. 2000000/10000

> 
>     2. i use my seafile server to share data with other users
>        in cases where i share a problematically named file with others, you are suggesting the receiver should rename the file or even the client could do it automatically. 

Alternatively, you may create a copy of file with name like "(conflicting file - invalid-file-name-blah-blah)". You do it automatically already in case of synchronization problems.

>  i'm assuming the file name change would also affect my local files, otherwise you'd have two different files. firstly, this would be  impossible with libraries you want to share read-only; especially if the source file system is mounted read-only also (i actually  do that). 

Hmm. If you have you source mounted read-only (e.g. Blu-ray drive), how you manage to rename invalid files (if any) there? 

> secondly, i would like to be the first to decide how to name my files, especially if it's not simply a single file but one that is supposed to be included or accessed by scripts or other processes. i would like to be aware of those changes, so i can also  adjust the respective scripts/processes. thirdly, if problematic file names would only be bugging receivers, i would probably try  to revert to the old, problemtic name, or keep naming new files in problematic ways, only to see them "magically" change   shortly after, until i get like a call from someone asking me to leave my files alone. 

I agree with all your arguments here. However... You tell "I would like to decide how to name my files". But new SF client disallows me to do the same - I can't give a valid name (in my O/S) to my file anymore. 

> therefore, if any other user can have a problem with a file name, all clients should tell. that should be done even without any other known users, they might only be added at a later time, i wouldn't want to suddenly have to rename a bunch of files then.

Said well: "IF". Let's repeat once again: IF!!! Not always!!!.

> so from my view this feature only makes sense if it's actually bugging everyone to stick to proper file names, and if you don't want that you should be able to deactivate it completely, at the risk of not being able to share content with other users.

Only one tiny addition - this feature must be turned off by default, because "IF".

**Comment by ckvsoft** [comment]
Hallo
Is there any information on how to downgrade Ubuntu without having to compile it yourself?

thanks

**Comment by Redsandro** [comment]
@ckvsoft commented:

> Is there any information on how to downgrade Ubuntu without having to compile it yourself?

@bertvandepoel's previous [suggestion](https://github.com/haiwen/seafile/issues/2451#issuecomment-851955714) does not work anymore:

> You simply `sudo apt update` then followed by `sudo apt install seafile-gui=8.0.1 seafile-daemon=8.0.1` to make apt downgrade the packages.

Unfortunately Seafile has removed 8.0.1 from their repository. I'm not sure why they don't host multiple older versions specifically for issues like this one. Just leave stable versions there for a year (or five), unless there's a major security issue.

**Comment by bertvandepoel** [comment]
The issue is fixed in 8.0.3 if you correctly enable "Hide Windows incompatibility paths Message" in your settings. I'm confused why people still wish to downgrade.

**Comment by Redsandro** [comment]
> I'm confused why people still wish to downgrade.

Mixed reported results, mixed messages, reports of warning messages that you don't want your users to have to deal with. Perhaps they forgot to lock 8.0.1 and received the update to 8.0.3.

If you maintain multiple machines, you'll just want wait until everyone reports being happy with the latest client before unfreezing 8.0.1.

Ideally 8.0.4 will make everything automated so you don't have to instruct users to force resync, delete logs, reboot etc.

Personally I think Seafile should **enable _"Hide Windows incompatibility paths Message"_  by default on pre-existing installations on Linux** so that everything will stay the same, and only disable it on new installations.

Or for extreme UXing, the option should be _"**Show** Windows incompatibility paths Message"_ and only be enabled on new installations unless it was previously enabled.

**Comment by ckvsoft** [comment]
> The issue is fixed in 8.0.3 if you correctly enable "Hide Windows incompatibility paths Message" in your settings. I'm confused why people still wish to downgrade.

Oh. I did not See this Option ;-) 
I will try this out.
Thx
Lg chris

**Comment by YamashitaRen** [comment]
> The issue is fixed in 8.0.3 if you correctly enable "Hide Windows incompatibility paths Message" in your settings. I'm confused why people still wish to downgrade.

Maybe you would get it if you were reading other people comments...
https://github.com/haiwen/seafile/issues/2451#issuecomment-874667166

So can we just please stop the disinformation, the spam, and simply require of the devs to unfuck Seafile.

**Comment by bertvandepoel** [comment]
> > The issue is fixed in 8.0.3 if you correctly enable "Hide Windows incompatibility paths Message" in your settings. I'm confused why people still wish to downgrade.
> 
> Maybe you would get it if you were reading other people comments...
> [#2451 (comment)](https://github.com/haiwen/seafile/issues/2451#issuecomment-874667166)
> 
> So can we just please stop the disinformation, the spam, and simply require of the devs to unfuck Seafile.

What you are referring to I would consider a separate issue completely. I understand that for many this is all one big issue, but as the maintainers from haiwen have made clear, they consider this issue solved by this setting. I would suggest you file separate issues. 

I would also like to remind you that as this is an open source project that is available to you without charge, that it seems somewhat unfair that you are demanding that the developers fix something. The whole point of FOSS is that you are free to fix something yourself or to hire someone to fix it for you. I would therefore suggest you file a separate issue (or several) concerning your points (some of which, I personally find quite valid, but I still consider off-topic for this issue), and consider also filing Pull Requests with proposed resolutions. 

I'm actually quite surprised @killing or another haiwen member hasn't closed this issue yet. Especially since it seems you are now resorting to a somewhat personal attack, which I obviously don't appreciate.

**Comment by Redsandro** [comment]
We all know how difficult the road to good open source software can be. So when there is something good, it's a bit frustrating when devs take a shortcut and forego best practices (such as _don't break things, but when you do, don't do it in a [patch release](https://semver.org/),_ or _make breaking changes opt-in rather than opt-out for existing projects_) and cause a lot of headaches in the process.

@bertvandepoel I'm not sure the price tag is relevant here. If I make very nice vases and sell them at a price, but I give you one for free, you can still be rightfully frustrated when someone breaks it. Especially when that someone only cleans up half the mess and "considers it cleaned up". :wink:

**Comment by Jasper-Ben** [comment]
> @Jasper-Ben After deleting local logs and restarting again it seems to work fine. Not sure if deleting the logs was the solution or just restarting a few times.

I tried deleting the logs, restarting, unsyncing and resyncing the library, unchecking and rechecking the "Hide Windows incompatibility paths Message". So far no luck.

**Comment by Jasper-Ben** [comment]
> What you are referring to I would consider a separate issue completely. I understand that for many this is all one big issue, but as the maintainers from haiwen have made clear, they consider this issue solved by this setting. I would suggest you file separate issues.

I'd disagree on this though. The issue is clearly related to the originally made change and thus I would consider the bugfix incomplete.

**Comment by ilikegitlab** [comment]
Got the same issue. What is worse is that it very much looks like that Windows systems are uploading files that are incompatible with windows systems.... (I get the error on folders that i never touched, but now it seems it cannot sync the folder).



This is a mess. I'll have to revert as well.

**Comment by bertvandepoel** [comment]
@PrzemekSkw do you mean you flipped the appropriate setting in the client and the notifications still persist, or did you not notice the setting yet?

**Comment by PrzemekSkw** [comment]
I noticed that I still have `!` sign on tray icon even if on seafile-client everything looks OK. Only on one laptop with archlinux.
Regards.

**Comment by ToxicMushroom** [comment]
The error doesn't even tell me which file causes it 
![image](https://user-images.githubusercontent.com/32853531/190850803-5a93c1ed-3cc7-4a66-ae85-8aba260b62f4.png)
I have 5000 files in this directory, idk what to look for.

**Comment by nicksukie** [comment]
FYI for anyone getting that message within the client, here the mac command to find the culprit files: 
`find /my/directory/path -type f -name '<>:"\\|?*]*'`

**Comment by akostadinov** [comment]
@nicksukie , it doesn't work for me on linux and reading that pattern I doubt it works on mac too.

This seems to work with GNU find (but I haven't extensively tested it):
```
find /my/directory/path -regex '.*[<>:"\\|?*'$'\b'$'\t''].*'
```

It would be good though if seafile allows for renaming such files. Maybe user can choose the character mapping.

**Comment by killing** [comment]
Update: This message is now disabled by default with Seafile 9.0.10 and SeaDrive 3.0.12.
