### ISSUE TITLE
Is it possible to deploy Seafile Web at Non root domain using https?

### ISSUE THREAD

**Issue by dominikholler** [haiwen/seafile#250]
Is it possible to deploy seafile web at non root domain using https? Looks like [issues 38](https://github.com/haiwen/seafile/issues/38) is still forcing a redirect over http.

**Comment by daald** [comment]
> I wonder why nobody else get this problem, maybe there is an error in my configuration. I tried to follow the instructions of the wiki exactly.
It seems that the problem is still here, 4 years later.

There seems to be solutions:

- use fastcgi and parameter `fastcgi_param HTTPS on;`, but the manual states: "If you are using FastCGI which is not recommended [...]"
- use `rewrite ^ https://$http_host$request_uri? permanent;` on your port 80 server. unfortunately, I don't have one
- use `add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";` which is a security option but works as a _very dirty workaround_ for this bug. it helps because the browser "fixes" the wrong url on-the-fly for security reasons

But the latter doesn't solve the origin problem:
```
$ curl -v https://myhost 
> GET / HTTP/1.1
> Host: myhost
> 
< HTTP/1.1 302 FOUND
< Location: http://myhost/accounts/login?next=/
```

**Comment by daald** [comment]
Finally, modifying Django config works:

Modify file seafile-server-6.2.2/seahub/thirdpart/Django-1.8.18-py2.7.egg/django/conf/global_settings.py:

Replace

    SECURE_PROXY_SSL_HEADER = None

by

    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')"

or something which is more safe:

    SECURE_PROXY_SSL_HEADER = ("http_safety_token", "whateveryoulikesh0liM4ahdo6ShethoC4she7")'

and set the header in your webserver config, in my case nginx:

    proxy_set_header   X-Forwarded-Proto https;

**Comment by shoeper** [comment]
Does it also work when setting it in conf/seahub_settings.py?

**Comment by daald** [comment]
@shoeper Indeed, conf/seahub_settings.py also works and is the file to use :-)

**Comment by shoeper** [comment]
@daald Maybe you could submit a PR at https://github.com/haiwen/seafile-docs
