### ISSUE TITLE
Go fileserver: Folder or File is not deletable when there is a spurious utf-8 char inside the filename.

### ISSUE THREAD

**Issue by kiorky** [haiwen/seafile#2594]
reopening of #2584

`9.0.7` seems not to address the issue, my already uploaded and broken files are still not deletable both with the C and GO fileservers.

**Comment by feiniks** [comment]
Hello, this issue should have been fixed in version 9.0.7 and tested as well. Are you still failing to delete the same file? Are there any errors reported in fileserver.log?

**Comment by kiorky** [comment]
Yes, i'm still failing to delete them.

Nothing is related in the logs with both server implementations.

In the web ui, you see the file "sucessfully deleted", but if you refresh, you will see that file are not deleted and so coming back.

**Comment by feiniks** [comment]
I use go fileserver locally and both files and directories named "Tés_test1_eaccentuated_is_not_regular" can be deleted normally. You can check to see if seafile has been upgraded to version 9.0.7 normally and the go fileserver  is version 9.0.7.
Maybe you need to test deleting a re-uploaded file instead of deleting the existing one.The existing file was created by a previous version and may not be compatible with the current version's handling of utf-8.

**Comment by kiorky** [comment]
If you re read my initial message, that's exactly the problem and the bug still remain.

The proposed fix only normalize newly submitted files, which is fine, but do not address the initial bug which is to be able to delete already upload files. Now that the harm is already done, we need to be able to delete misuploaded files as we have now partially corrupted libraries.

**Comment by feiniks** [comment]
This is due to a problem with the encoding of the file name created by go before. The current version will also encode the file name normally, but the encoded file name is inconsistent with the previous storage, so there will be problems with deletion. If you want to delete this part of the file, you need to delete their parent directory instead so there will be no coding issues. Subsequent new files with such names can be processed normally.

**Comment by kiorky** [comment]
Nope as i said in #2584 neither direct parent container or the file can be deleted.

**Comment by feiniks** [comment]
What I mean is that you need to delete the b and c directories, you should delete the parent directory of the file in question.

**Comment by kiorky** [comment]
consider this structure using 9.0.4 Go fileserver
```sh
mkdir folder1é toto
for i in folder1é.md toto/folder1é.md folder1é/toto.md;do echo 123 > $i;done
```

drag'drop ujpload them to your library

upgrade to 9.0.7

The first level files & folders are still not deletable, only toto folder will be.

**Comment by killing** [comment]
It's fixed in newer versions.

**Comment by kiorky** [comment]
which commit(s) contains the fix ?

**Comment by kiorky** [comment]
@killing which commit(s) contains the fix ?
