### ISSUE TITLE
[web] embed

### ISSUE THREAD

**Issue by promethe42** [haiwen/seafile#466]
Hello,

do you have in the roadmap anything related to embedding some file using iframes à la Youtube?

Regards,

**Comment by shoeper** [comment]
Embedding stuff could lead to possible security issues.

**Comment by SteffenL** [comment]
Would you like to explain a bit more about that in detail just to satisfy our curiosity, @shoeper ?

Does this mean that this feature is not going to happen after all because there is a flaw in Seafile that can be exploited in its current state, and that flaw is not going to be fixed at all for some reason?

I am just asking for details because it may be a bit difficult to feel content with this sudden resolution.

**Comment by shoeper** [comment]
> I am just asking for details because it may be a bit difficult to feel content with this sudden resolution.

I'm currently cleaning up things a bit.

> Does this mean that this feature is not going to happen after all because there is a flaw in Seafile that can be exploited in its current state, and that flaw is not going to be fixed at all for some reason?

There is no bug I know of. Using html doesn't seem to be possible.

> Would you like to explain a bit more about that in detail just to satisfy our curiosity

The problem with handling resources from other sites is that making sure e.g. no bad javascript is being executed / no bad code is being loaded. Furthermore by allowing iframes an attacker could easily run phishing attacks that look trustworthy, because it e.g. looks like there would be hosted on the companies internal Seafile server.

**Comment by SteffenL** [comment]
Thank you for explaining, @shoeper!

Please correct me if I am wrong but I would just like to make sure that we understand each other.

I believe that the original request was to facilitate embedding of a resource (e.g. a video or audio file) hosted in Seafile, on another website. An example could be how YouTube gives you a code snippet (HTML) which can be pasted on any website that supports it. This would require anonymous access to the resource either via an iframe or direct access to it (HTML 5 audio/video).

I do not think that the original request was to embed anything on the Seafile server pages.

In my case, I also meant mostly the same thing, just that I wanted an embeddable file manager/viewer/uploader of some sort allowing anonymous access.

What do you think?

**Comment by shoeper** [comment]
I think I missunderstood it in this case. freeplant also interpreted it the wrong way. Thanks for clearifying it.

Did you try doing that by sharing a file and using ?dl=1 or ?raw=1?. I think those files should be includable on other sites.

**Comment by SteffenL** [comment]
Thank you, @shoeper!

I hope that your suggestion can help @promethe42 and other people who come across this issue!

Since a lot of users do not know what to do with the URL, the requested feature could still be pretty convenient. Maybe Seafile could help generate a piece of code that can easily be pasted on other websites.

I just realized that I should probably create a separate ticket about my own use-case.

**Comment by shoeper** [comment]
@SteffenL ok, then I'll leave this closed and it'll be more clear from your ticket what the idea is.

**Comment by rabb1t** [comment]
Guys, any updates on this? Hows it going? Can we embed videos yet?

**Comment by shoeper** [comment]
> Did you try doing that by sharing a file and using ?dl=1 or ?raw=1?. I think those files should be includable on other sites.

**Comment by rabb1t** [comment]
> > Did you try doing that by sharing a file and using ?dl=1 or ?raw=1?. I think those files should be includable on other sites.

Sure, both of these options lead to "`302 Found`" with redirection to the seafhttp backend. Even though "`Content-Disposition: inline`" and "`Content-Type: application/octet-stream`" headers are presents in the response, browser offers to download the file (`Google Chrome	83.0.4103.61 (Official Build) (64-bit)`)

It would be really nice if the user can click on the separate "generate embed code" button straight in the web ui.

**Comment by fostertiktok5** [comment]
> In my case, I wish to let anonymous users interact with a shared folder (browse, download, upload) from a remote site, e.g. a blog/CMS, without having to leave that site. There's an alternative to Seafile which has such a feature and a bunch of other goodies.





https://opencodes.space/questions/can-a-custom-flash-video-player-be-developed-to-stream-youtube-hosted-videos

**Comment by daemaetrae** [comment]
Hello, I was wondering if this feature is only missing in Community edition, or it's completely unavailable? I also want to embed a view of Seafile UI to my blog , giving visitors a chance to download files straight from the webpage of my site
