### ISSUE TITLE
Cannot set up selective sync in a library

### ISSUE THREAD

**Issue by jacks50** [haiwen/seafile#549]
Hi,

I got a problem when I tried to synchronise selectively some file in a library. I got a Library named "myLib" and inside it I have 3 files : file_1.txt, file_2.txt and file_3.txt.

> myLib
> 
> > file_1.txt
> > file_2.txt
> > file_3.txt

I created a "seafile-ignore.txt" file which specifies that file_3.txt should not be synchronised, just by adding "file_3.txt" in the "seafile-ignore.txt".

I tried the following cases :
- add "seafile-ignore.txt" in "myLib"
- add "seafile-ignore.txt" in "Seafile" client's folder
- remove the extension of the file in "seafile-ignore.txt" and so only keep "file_3"

In every case, the file has been downloaded in the client's folder and is synching. Did I made something wrong ?

PS : It would be a great feature if the client could manage this with simple checkboxes for every file, by selecting a synched library (like the image). What do you think ? The file would be created on the background and could prevent some mistakes. :)

Thank you in advance !

Attach :
![skydrive-selective-sync](https://f.cloud.github.com/assets/2487690/2195996/c164d7f4-98a8-11e3-96c9-71e3c8a69a62.png)

**Comment by niij** [comment]
I commented in #239 but just realized it is closed... It appears that selective sub sync is now available for the [community version](https://www.seafile.com/en/product/private_server/).  But it behaves in a confusing manner where the selective folders are synced to the ROOT of the seafile directory, instead of the directory tree being built out to the selected folders.  Basically what @seanmadsen was talking about earlier in this thread.  Dropbox and Onedrive build out the directory structure correctly, if a reference is helpful.

If you have the below directory structure and want to only sync the 2015 files you will have 2015Tax and 2015Audit in your seafile/ root directory.
- seafile/
  - Taxes/
    - 2014Tax/
    - **2015Tax/**
  - Auditing/
    - 2014Audit/
    - **2015Audit/**



Current behavior when syncing 2015Tax and 2015Audit is:
- seafile/
  - 2015Tax/
  - 2015Audit/

Expected behavior:
- seafile/
  - Taxes/
    - 2015Tax/
  - Auditing/
    - 2015Audit/

**Comment by shoeper** [comment]
> Sub-libs do not solve it sufficitently, because they are not displayed hirachially below their parent lib, but rather on the same level.

This is all about how you do it. They can be stored anywhere on your computer.
