### ISSUE TITLE
.seafile-ignore.txt in addition to seafile-ignore.txt

### ISSUE THREAD

**Issue by seebi** [haiwen/seafile#561]
Hi there,

can we have a dotted seafile-ignore.txt in addition to seafile-ignore.txt file in order to avoid visibility on unix systems?

best

ST

**Comment by priyadarshan** [comment]
:+1: for adding syntax `.seafile-ignore` to the already present `seafile-ignore.txt`. In this way Windows users will still be fine, while OS X, Linux, iOS etc users will feel at home, since the `ignore` file will follow the industry standard (dot notation).

We are testing the `sea-file` server on Ubuntu, and it is quite troublesome to have to tell people that "seafile-ignore.txt" is NOT part of the real content, but a "visible config file".

Thank you!

**Comment by ikcalB** [comment]
@Crazyphil idk whether it's possible to create a file starting with a dot using library calls (at least those files are perfectely valid, as soon as they are on an NTFS [copied from linux, i.e.])

still I support the need for ignore list management!
(as well as a generalized configuration)
+1

if seafile is going to stick with the ignore file, I also beg for a dotted version.
+1

**Comment by kateyy** [comment]
On windows you can create files without a "base" name on the command line (rename) or using library calls. It's just the windows explorer that forbits it. So I think it would be fine to use the ".seafile-ignore" name.
Plus, you could add a simple GUI to the client that allows to create/edit this file without a need to explain unexperienced users how to access hidden files.

**Comment by ikcalB** [comment]
@kateyy thanks for clarifying!
