### ISSUE TITLE
Seafile UI partially working when VPN starts after program

### ISSUE THREAD

**Issue by lzap** [haiwen/seafile#578]
Hello,

I use Seafile over OpenVPN (Windows clients). When I start Seafile before OpenVPN connection (e.g. autostarting Seafile while initiating VPN afterwards), everything works just fine (tray icon shows excalamation mark until VPN is connected and then sync and shows "ok" icon).

But when I try to open UI, the main pane is "loading" forever and all I see is the loading spinner. Clicking on the refresh button does not work. It is frozen somehow.

Minor issue.

**Comment by ACinnamonUserInUK** [comment]
I found that turning off the Windows firewall solved this problem, although:

1. one has to do that in the right way (simply disabling the Windows service that provides the firewall blocks all traffic);
2. every time the VPN gets turned back on, that Windows firewall comes back on and needs disabling again (and I've managed, with considerable difficulty, to automate this); 
3. my third-party firewall, that I use instead of the Windows one, also blocks Seafile. I've written to the makers of that firewall about that problem.

All of this is a real pain, though another program I have - so, not just Seafile - suffers from problem 2 as well; so perhaps Seafile is not wholly to blame (though I am on the verge of being so confused by multiple firewalls, multiple computers and multiple network programs that it is hard to tell what is going on!).
