### ISSUE TITLE
media files for iOS must support byte-range requests

### ISSUE THREAD

**Issue by NNois** [haiwen/seafile#583]
Hi,
On a test environement i was able to reproduce the error given by your http server with video media files on iOS and Android...

You added correctly missing mime types on 2.1.5 but this doesn't solved the issue...

But futur is bright because this error is volved when the server supports byte-range request, and i admit, it would be very great if seafile could do this, this open seafile for video streaming.

https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html

http://stackoverflow.com/questions/3128906/mp4-plays-when-accessed-directly-but-not-when-read-through-php-on-ios

**Comment by NNois** [comment]
Hi guys,
Sadly i've saw this one on roadmap for 4.0 then 4.1 then 5 ?
Interracting with files isn't a priority for seafile ???

**Comment by shoeper** [comment]
I'm not sure what you're talking about. My feeling about this project is exactly the other way around. Seafile cares very much about file handling. Other projects I won't mention here do only care about as many features as possible.

**Comment by NNois** [comment]
@shoeper this is in the subject, we just can't stream a video with seafile, you have to download it ! The web player so is clamped just from a play to the start function on desktop computers, plus on mobile devices side videos don't play at all because the server needs to support a bit-range request on files.
I guess this is also a problem on custom setups where we need to read only from a specific part of a file

**Comment by shoeper** [comment]
I know that streaming is currently not possible. But streaming is imho not seafiles core competence/functionality. And the core functionality which is imho the desktop client including a stable sync algorythm has always been greatly improved and supported. Since v3 I didn't have any problem thereby.

It would be a nice feature indeed, but I could also imagine that it is much work to include byte-range requests in a manner it isn't a too big performance drawback. Because of the block storage it is not possible to just open a file, seek to position x and send data till byte y. That also seems to be the reason why it has not been implemented so far.

And behind seafile also is a company. And they have to make money to further develop seafile - to improve the community edition, so I can understand it when they say we first have to improve for example LDAP or similiar features. Don't think companies are buying seafile to let their employees watch streams. Of course there are enough cases where it would be a benefit to have byte-range requests (e.g. to continue large file downloads via seahub made by customers having a short disconnect). But without some core functionality like LDAP (afaik LDAP works now but that wasn't always the case and there may be other similar features which are must have for companies) many companies wouldn't even think about buying seafile, while they can live with some drawbacks on seahub because of the great stable client.

**Comment by atimonin** [comment]
It seems that it may be done rather simply setting content-type not simply "octet-stream", but something like "video/avi" or "video/mpeg"

**Comment by shoeper** [comment]
Yeah ok, would have been a fix before, but this doesn't sense anymore.

**Comment by atimonin** [comment]
Was fixed for audio, not video. Why "desn't sence"?

**Comment by shoeper** [comment]
With byte range requests it is fixed for video and audio.

**Comment by fuzzlux** [comment]
Byte range requests seem trivial from a server API standpoint.  

As far as companies streaming video, I think it's safe to say collaboration in more media centric business models would love this.  Production facilities, ad agencies, and their clients deal with exchange cuts of video and audio every day.

I understand these are likely not your target client markets, but the use case for professional organizations is there.

I might even build streaming Seafile media players for fun.  Private cloud steaming FLACs are motivating enough for me to do this.

**Comment by shoeper** [comment]
Byte range requests are already supported and weren't trivial in seafile afaik.

**Comment by freeplant** [comment]
Since byte range request is already supported. I close the issue.
