### ISSUE TITLE
Don't sync until a restart of the client client (3.1.5 Windows)

### ISSUE THREAD

**Issue by NNois** [haiwen/seafile#856]
Hi from version 3.0 now it's easy to broke the sync process:
- Put a large file (like 200Mo) + next seconds add some other files
- now the library don't sync until a full restart of the client (3.1.5 Windows)
  or
- "sync now" even don't works but "desactivate the auto sync" followed by "activate the auto sync" works and initiat correctly the sync process...

applet.log
[09/17/14 14:53:40] request failed for http://xxx.fr/api2/events/: status code 404

ccnet.log
[09/17/14 14:53:37] ../common/peer.c(763): Delayed update from local-2(d0b465df), id is 1040, 500 Shutdown

**Comment by GITchristoph** [comment]
Hi
I am trying to sync with the following setup:
- Seaf-cli based on 4.0.6 running on a Raspi
- on Raspi a windows share gets mounted with cifs to /mnt/share (read and write permissions)
- /mnt/share is now supposed to get synced

Problem:
- sync does not detect changes or new files once it synced one time
- sync only works after restart of seaf-cli


Is that the expected behaviour, because of the samba share?
Should I not use this setup then or is there a possibility to do a "do scan"?

**Comment by shoeper** [comment]
Samba shares don't work. You could automatically restart seafile-cli from time to time. Or you could ask the team to add sync now in the cli (it's available in the client). According to https://seacloud.cc/group/3/wiki/seafile-cli-manual/ this option is not available at the moment.

Having a FileSystemWatcher for Samba shares on client side is never reliable. So this is no seafile specific problem.

**Comment by GITchristoph** [comment]
Thanks and understood.
