### ISSUE TITLE
sync the same sub-library into multiple local folders

### ISSUE THREAD

**Issue by sigmoidal** [haiwen/seafile#863]
I have layout on 4 different computers that is as follows:

D:\stuff

where I place directories for various files and so on. In addition I have an external drive in which I have "stuff" also, as say I:\stuff which I may connect on any of the 4 pcs as well as use it on computers that don't have the D:\stuff layout at all.

The use case here is that I want to keep up to date the contents of any of these "stuff" folders with Seafile, be it in D:\stuff or I:\stuff . I want all these "stuff" locations to be updated. The problem is that there is no feature to allow me to choose to sync the same cloud directory locally multiple times.

Although I see this being shot down by most cloud software developers, because they claim cloud software isn't supposed to be used as a folder sync tool, this is in my opinion wrong. There should be no restrictions; cloud syncing should be more permissive and agnostic of where I choose to store my data. 

I hope you will take it into consideration if you have time in the future.

thanks a lot and keep up with the excellent work on Seafile!

**Comment by ikcalB** [comment]
+1

**Comment by oliverrahner** [comment]
Another +1
My use case is syncing Flash Local Object Files (those under AppData\Local\Macromedia\...) between computers **and** browsers on the same computer (because Chrome uses PepperFlash by default, which has a separate directory).
I used to use Dropbox and create junctions inside the original store location to point to the Dropbox dir, but that is a hassle to do and also means I cannot use Protected Mode for Flash, which is a security issue.
