### ISSUE TITLE
Seafile behind NAT with HTTPS sync

### ISSUE THREAD

**Issue by sebiii** [haiwen/seafile#984]
Hi,

I have Seafile running behind a NAT with port forwarding and different name resolutions:
internally: example.org is resolving to 192.168.1.X
externally: example.org is resolving to some public IP. 443 Port is forwarded to 192.168.1.X
SERVICE_URL ist set to https://example.org

HTTPS sync in the internal network works just fine, but when I try to sync from outside the network I found the following in the seafile.log:

[12/22/14 13:03:33] http-tx-mgr.c(327): libcurl failed to GET https://192.168.1.X/seafhttp/protocol-version: Couldn't connect to server.

Obviously, accessing 192.168.1.X from the internet cannot work. Is it possible that the seafile server provides the "https://192.168.1.X/seafhttp/protocol-version" URL which then is not accessible by the client because it is in a different network?

Thanks in advance,
Sebastian

**Comment by jonaslt** [comment]
I second that. Got the same problem running Seafile in Ubuntu VM on Windows PC and using Windows Client. It simply is trying to use local IP for HTTPS syncs instead of using WAN IP or set hostname.

**Comment by killing** [comment]
@lins05 Perhaps seafile applet passes the resolved address to seaf-daemon?

**Comment by killing** [comment]
@jeroenj What do you use for server address when syncing inside NAT? The domain name or the IP address?

**Comment by jonaslt** [comment]
I use hostname, which resolves to WAN IP. It seems that Seafile server sends to the client its local LAN IP to be used for HTTP SYNC instead of hostname.

**Comment by sebiii** [comment]
I have tried it with both WAN IP and hostname. In both cases I get 

libcurl failed to GET https://192.168.1.88/seafhttp/protocol-version

The setting of SERVICE_URL does not seem to change this either.

**Comment by freeplant** [comment]
Seafile client uses the server URL you entered when you added the account at the client side. What address do you use for the account?

**Comment by sebiii** [comment]
When I first set up the account I was using it just in my internal network. Later, I changed the server URL on the client side.

Does that mean I have to  add a new account in the client instead of changing the server URL of the existing one?

**Comment by jonaslt** [comment]
Yes, it could be that I have changed the account settings (I may have used an IP before) - it may be that the client is using an older entered IP - I will try to test that now after reinstalling the client.

**Comment by jonaslt** [comment]
Re: [seafile] Seafile behind NAT with HTTPS sync (#984)


Hi,

No, I did do right-click and edited the URL through "Account Settings" in Windows Client GUI.


Sunday, January 4, 2015, 3:41:49 PM, you wrote:





When I first set up the account I was using it just in my internal network. Later, I changed the server URL on the client side.
Does that mean I have to add a new account in the client instead of changing the server URL of the existing one?

**Comment by lins05** [comment]
@freeplant I guess it's because we add repo property `server-url` when we implement file sync over http. When the user changes the account url through seafile applet, only "relay-addr" is updated, but we should also update "server-url" here. 

https://github.com/haiwen/seafile/blob/v4.0.5/daemon/repo-mgr.c#L4524

**Comment by jonaslt** [comment]
Yes, after reinstalling and adding the server with appropriate hostname now it seems it works fine.

**Comment by lins05** [comment]
We have fixed this and would release it in the next version.
